### ISSUE TITLE
<br>标签现在是不是还不支持？

### ISSUE THREAD

**Issue by lyw2019AAA** [asasugar/HPRichText#1]
目前还在开发中吗，我看br标签还不支持

**Comment by asasugar** [comment]
> 目前还在开发中吗，我看br标签还不支持

我加一下~等v1.0.2版本

**Comment by asasugar** [comment]
> 目前还在开发中吗，我看br标签还不支持

![image](https://github.com/asasugar/HPRichText/assets/27256120/249fe081-a8aa-492a-9423-a04d3c21bc0d)
我试了一下没问题~
