### ISSUE TITLE
关于整段html标签文字需要设置 maxLine

### ISSUE THREAD

**Issue by oafixiaoxin** [asasugar/HPRichText#12]
有这样一段标签文字：
<p>11111111</p>
<p>222222</p>
<p>33333</p>
<p>444444</p>
<p>5555555</p>
<p>666666</p>

在UI中我只需要显示前3行，可以整段html标签支持maxLine和TextOverflow吗

**Comment by asasugar** [comment]
<div style="-webkit-line-clamp: 3;overflow: hidden;text-overflow:ellipsis;white-space: nowrap;">多行文本显示省略号多行文本显示省略号多行文本显示省略号</h1>
