### ISSUE TITLE
字体大小适配问题

### ISSUE THREAD

**Issue by showdy** [asasugar/HPRichText#14]
由于手机型号差异，不同的手机宽度不一致，而ui图纸一般按照750px（或者其他）设计，为文本设置fontsize为px单位会有问题（实际开发一般转为lpx或者vp），能否适配lpx/vp之类的单位，baseFontSize能否适配lpx单位。

**Comment by asasugar** [comment]
> 由于手机型号差异，不同的手机宽度不一致，而ui图纸一般按照750px（或者其他）设计，为文本设置fontsize为px单位会有问题（实际开发一般转为lpx或者vp），能否适配lpx/vp之类的单位，baseFontSize能否适配lpx单位。

1

**Comment by asasugar** [comment]
@State richTextOption: RichTextOption = {
    content: `
      <span style="font-size:12.5px;"><span style="color:#666666;line-height:1.5;"><span style="font-size:12.5px;"><span style="color:#666666;"></span></span></span><span style="color:#666666;line-height:1.5;">【超级0卡糖*·低负担·0咖啡】</span><br />
      <br />
      <span style="color:#666666;line-height:1.5;">不含咖啡的友好小铁</span><br />
      <span style="color:#666666;line-height:1.5;">陪伴午后的闲暇时光</span><br />
      <br />
      <span style="color:#666666;line-height:1.5;">「超级0卡糖*」原创定制</span><br />
      <span style="color:#666666;line-height:1.5;">果味清爽沁甜</span><br />
      <br />
      <span style="color:#666666;line-height:1.5;">感受青提风味在奶香和椰香中游走</span><br />
      <span style="color:#666666;line-height:1.5;">轻盈地，过夏天</span><br />
      <br />
      <span style="color:#666666;line-height:1.5;">*本品使用0卡青提风味饮料浓浆（含赤藓糖醇）</span><br />
      </span>
    `,
    basePixelUnit: 'vp', // px转化成vp像素单位
    basePixelRatio: 1, // 像素比
    imageProp: {
      webp: true,
    }
  };
