### ISSUE TITLE
a标签链接点击无效

### ISSUE THREAD

**Issue by liyun1030** [asasugar/HPRichText#15]
有如下字符串：
<p>today大部分时间都在睡觉，全天清醒的时间只有1小时左右。</p><p><span>点击右边文字了解更多：</span><a href="meiyou:///web?params=eyJ1cmwiOiJodHRwOi8vdGVzdC1teXlxLnNlZXlvdXlpbWEuY29tL3RpcHMyL2NsaWVudD90aXBzX2lkPTEyMzUyODkma2V5cz0zMmFjNDMwMTA5NDc5NGI0MDk5YWY3Y2IwZmU3N2RmMjBjNjBmOGZhJm15d3RiX25hbWU9dGlwczIifQ==" target="_blank"><span>第1周养育要点</span></a></p>

使用HPRichText显示此内容，其中a标签有链点，点击无回调，什么原因？是HPRichText不支持？

**Comment by asasugar** [comment]
> 有如下字符串：
> 
> today大部分时间都在睡觉，全天清醒的时间只有1小时左右。
> 
> 点击右边文字了解更多：第1周养育要点
> 
> 使用HPRichText显示此内容，其中a标签有链点，点击无回调，什么原因？是HPRichText不支持？

HPRichText暴露了onLinkPress回调，需要你这边自己处理点击之后的事件，详见README文档

**Comment by liyun1030** [comment]
onLinkPress加了根本没反应
