### ISSUE TITLE
简单引用报错 

### ISSUE THREAD

**Issue by winnxiegang** [asasugar/HPRichText#18]
HPRichText({
          richTextOption: {
            content: '我是改变之后的数据，如通过ajax请求返回的数据',
            imageProp: {
              webp: true,
            }
          },
          needScroll: true,
          onLinkPress: (e) => {
            return e;
          }
        }) 这样引用就报错 
![图片](https://github.com/asasugar/HPRichText/assets/14342300/5a95461f-0708-4723-83ca-8f2a29c6a24a)

**Comment by asasugar** [comment]
> HPRichText({ richTextOption: { content: '我是改变之后的数据，如通过ajax请求返回的数据', imageProp: { webp: true, } }, needScroll: true, onLinkPress: (e) => { return e; } }) 这样引用就报错 ![图片](https://private-user-images.githubusercontent.com/14342300/336776455-5a95461f-0708-4723-83ca-8f2a29c6a24a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODQ3MjQsIm5iZiI6MTcxODE4NDQyNCwicGF0aCI6Ii8xNDM0MjMwMC8zMzY3NzY0NTUtNWE5NTQ2MWYtMDcwOC00NzIzLTgzY2EtOGYyYTI5YzZhMjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA5MjcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMzBkNDIzNGM3YzhkYmY3NzMwMDE5OTBmMWUyZWU2ODc1OTJkNjM4NzNhMGNkY2Y4ZmFjZjU2MmVmZjRhYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SBOSSALQO40Vj4FVM_YyVZgnGZ8A1d9F7CCw79EKZVA)

提供一下 IDE版本，sdk版本，以及最小示例

**Comment by winnxiegang** [comment]
![图片](https://github.com/asasugar/HPRichText/assets/14342300/dfe45eaa-a9b7-462f-a3ee-5779913b9c94)
官方最新的开发工具和模拟器。

**Comment by winnxiegang** [comment]
![Uploading 图片.png…]()
就是简单使用 放在竖直列表中

**Comment by winnxiegang** [comment]
![图片](https://github.com/asasugar/HPRichText/assets/14342300/51850762-dd33-45e0-a2dc-808a45e60e35)

**Comment by asasugar** [comment]
> ![图片](https://private-user-images.githubusercontent.com/14342300/344908350-51850762-dd33-45e0-a2dc-808a45e60e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzAyOTksIm5iZiI6MTcyMDQyOTk5OSwicGF0aCI6Ii8xNDM0MjMwMC8zNDQ5MDgzNTAtNTE4NTA3NjItZGQzMy00NWUwLWEyZGMtODA4YTQ1ZTYwZTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA5MTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZWI0ZGQ1OGFhODJhY2I3N2MzYjc4MTU4M2FlOWRmN2I0YmM0N2NmZGE3NmY3MTJmODZmNGJmZGIzOGI4YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-j-5e-_0V4nfhbKP-v7pkXJFp4Uku6HJIAPtx1_0CzA)

<img width="1447" alt="image" src="https://github.com/asasugar/HPRichText/assets/27256120/10023756-a283-4e44-8c61-b1c77e43d8a9">
需要迁移历史版本

**Comment by asasugar** [comment]
https://github.com/asasugar/HPRichText/commit/61b7628ae113bf8e04d6cc3a131dd5cef646fbfa
