### ISSUE TITLE
解析html文本时候，线程卡死

### ISSUE THREAD

**Issue by 0xmou** [asasugar/HPRichText#2]
解析的文本：
```html
<div class="view-fullmodle"> <a class="confirm-btn mb10" ttname="bbs_detail_onlylzpic"
                href="https://jiaxing.19lou.com/creampic-fid-779-t-97041711089344239-p-97731711089344480-nodigest-all-dateline.html"><span>只看楼主大图</span></a>
</div>
<div>
        <div>今天是南湖天地咖啡节第一天，中午就跟小伙伴噶闹忙去了。今年品牌明显多了，一时都不知道应该喝哪几家，随意感受了一下。<br><br>先说，不爱咖啡的小伙伴谨慎冲。场地很小，人超多，人气旺的摊位都要排队。价格不便宜，一般都是38-48元的价位。<br><br>第一家喝了云南的谙客咖啡，这家去年就在。还记得去年我喝的是“有风在大理”，去年要68元，今年还有，只要48元了，伤心。今年的新品是“繁花”，依然是68元。节省的我选了非新品“菇的咖啡”，48元，大致是菌菇风味的底+朗姆酒+啤酒花的沫，整体野生菌味很明显，我挺爱的，但是我的小伙伴们没一个爱菇味。买一杯咖啡，就送了包包和贴纸，好感度拉满。<img
                        src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2852x2363-143517_v3_12591711089317660_6c54216859ffc3fd36822ac28584b420.jpg"
                        data-filename="/2024/03/22/14/middle_2852x2363-143517_v3_12591711089317660_6c54216859ffc3fd36822ac28584b420.jpg"
                        data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
        </div>
        <div><br></div>
        <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2700x3012-143517_v3_17451711089318007_c776635789c2912a64c34bfdc0d7d516.jpg"
                        data-filename="/2024/03/22/14/middle_2700x3012-143517_v3_17451711089318007_c776635789c2912a64c34bfdc0d7d516.jpg"
                        data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
        </div>
        <div><br></div>
        <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4096x5461-143536_v3_20191711089341180_f63d670a1adef88fca9934bea4f6d92f.jpg"
                        data-filename="/2024/03/22/14/middle_4096x5461-143536_v3_20191711089341180_f63d670a1adef88fca9934bea4f6d92f.jpg"
                        data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
        </div>
        <div><br></div>
        <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4032x3024-143518_v3_12281711089318759_50040f301f3e70a67ca670916be22f6f.jpg"
                        data-filename="/2024/03/22/14/middle_4032x3024-143518_v3_12281711089318759_50040f301f3e70a67ca670916be22f6f.jpg"
                        data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
        </div>
        <div><br>第二家喝了广州的&amp;U。我们人多，把“黑色森林”、“柏林少女”、“荔城挂绿”、“花园派对”都点了。个人口味比较喜欢黑色森林（液体巧克力蛋糕味）和荔城挂绿（很清爽）。</div>
        <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4096x3483-143522_v3_17951711089322833_508c0acfee35f996fdf9fb7c0cf43d72.jpg"
                        data-filename="/2024/03/22/14/middle_4096x3483-143522_v3_17951711089322833_508c0acfee35f996fdf9fb7c0cf43d72.jpg"
                        data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
        </div>
        <div><br></div>
        <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2542x2738-143514_v3_12201711089314426_0977dcd7d4a5a6a8140dc5feae1c7a96.jpg"
                        data-filename="/2024/03/22/14/middle_2542x2738-143514_v3_12201711089314426_0977dcd7d4a5a6a8140dc5feae1c7a96.jpg"
                        data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
        </div>
        <div><br></div>
        <div>第三家喝了熊煮咖啡。主理人是世界咖啡冲煮大赛的获奖选手，必须来杯手冲。爱我中华，选了云南的豆，是我喜欢的口味。</div>
        <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4096x2393-143518_v3_16871711089318560_136209cd04576230c869ff66662cd572.jpg"
                        data-filename="/2024/03/22/14/middle_4096x2393-143518_v3_16871711089318560_136209cd04576230c869ff66662cd572.jpg"
                        data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
        </div>
        <div><br></div>
        <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_3406x5118-143535_v3_18731711089337968_26a405c554b985d3ef33e9f07bce2717.jpg"
                        data-filename="/2024/03/22/14/middle_3406x5118-143535_v3_18731711089337968_26a405c554b985d3ef33e9f07bce2717.jpg"
                        data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
        </div>
        <div><br></div>
        <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_3010x3419-143514_v3_17111711089314289_9a7d524e4dd6d48d1797648e563513f8.jpg"
                        data-filename="/2024/03/22/14/middle_3010x3419-143514_v3_17111711089314289_9a7d524e4dd6d48d1797648e563513f8.jpg"
                        data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
        </div>
        <div><br></div>
        <div>蹭拍一张小伙伴买的方象咖啡，颜值挺高。<img
                        src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_3479x2359-143515_v3_13401711089315275_3700ae692f054be7677ee281af930caa.jpg"
                        data-filename="/2024/03/22/14/middle_3479x2359-143515_v3_13401711089315275_3700ae692f054be7677ee281af930caa.jpg"
                        data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
        </div>
        <div><br></div>
        <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2268x3024-143519_v3_10921711089319424_6f693d390a2469419847ef420319fdaf.jpg"
                        data-filename="/2024/03/22/14/middle_2268x3024-143519_v3_10921711089319424_6f693d390a2469419847ef420319fdaf.jpg"
                        data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
        </div>
        <div><br></div>
        <div>另外还有贵州的咖啡旅人（刺梨咖啡很有兴趣）、北京的隐咖啡（深烘咖啡专门店，苦的很有礼貌）、大连的车轮子咖啡（微醺小车轮看着不错）等等，实在喝不过来了，周末再去试试。<br></div>
</div>
```

下面错误日志：
![FaultLog](https://github.com/asasugar/HPRichText/assets/93482443/f146518d-dd04-460f-a674-6584bc709b9a)

**Comment by asasugar** [comment]
> 解析的文本：
> 
> ```
> <div class="view-fullmodle"> <a class="confirm-btn mb10" ttname="bbs_detail_onlylzpic"
>                 href="https://jiaxing.19lou.com/creampic-fid-779-t-97041711089344239-p-97731711089344480-nodigest-all-dateline.html"><span>只看楼主大图</span></a>
> </div>
> <div>
>         <div>今天是南湖天地咖啡节第一天，中午就跟小伙伴噶闹忙去了。今年品牌明显多了，一时都不知道应该喝哪几家，随意感受了一下。<br><br>先说，不爱咖啡的小伙伴谨慎冲。场地很小，人超多，人气旺的摊位都要排队。价格不便宜，一般都是38-48元的价位。<br><br>第一家喝了云南的谙客咖啡，这家去年就在。还记得去年我喝的是“有风在大理”，去年要68元，今年还有，只要48元了，伤心。今年的新品是“繁花”，依然是68元。节省的我选了非新品“菇的咖啡”，48元，大致是菌菇风味的底+朗姆酒+啤酒花的沫，整体野生菌味很明显，我挺爱的，但是我的小伙伴们没一个爱菇味。买一杯咖啡，就送了包包和贴纸，好感度拉满。<img
>                         src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2852x2363-143517_v3_12591711089317660_6c54216859ffc3fd36822ac28584b420.jpg"
>                         data-filename="/2024/03/22/14/middle_2852x2363-143517_v3_12591711089317660_6c54216859ffc3fd36822ac28584b420.jpg"
>                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
>         </div>
>         <div><br></div>
>         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2700x3012-143517_v3_17451711089318007_c776635789c2912a64c34bfdc0d7d516.jpg"
>                         data-filename="/2024/03/22/14/middle_2700x3012-143517_v3_17451711089318007_c776635789c2912a64c34bfdc0d7d516.jpg"
>                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
>         </div>
>         <div><br></div>
>         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4096x5461-143536_v3_20191711089341180_f63d670a1adef88fca9934bea4f6d92f.jpg"
>                         data-filename="/2024/03/22/14/middle_4096x5461-143536_v3_20191711089341180_f63d670a1adef88fca9934bea4f6d92f.jpg"
>                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
>         </div>
>         <div><br></div>
>         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4032x3024-143518_v3_12281711089318759_50040f301f3e70a67ca670916be22f6f.jpg"
>                         data-filename="/2024/03/22/14/middle_4032x3024-143518_v3_12281711089318759_50040f301f3e70a67ca670916be22f6f.jpg"
>                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
>         </div>
>         <div><br>第二家喝了广州的&amp;U。我们人多，把“黑色森林”、“柏林少女”、“荔城挂绿”、“花园派对”都点了。个人口味比较喜欢黑色森林（液体巧克力蛋糕味）和荔城挂绿（很清爽）。</div>
>         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4096x3483-143522_v3_17951711089322833_508c0acfee35f996fdf9fb7c0cf43d72.jpg"
>                         data-filename="/2024/03/22/14/middle_4096x3483-143522_v3_17951711089322833_508c0acfee35f996fdf9fb7c0cf43d72.jpg"
>                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
>         </div>
>         <div><br></div>
>         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2542x2738-143514_v3_12201711089314426_0977dcd7d4a5a6a8140dc5feae1c7a96.jpg"
>                         data-filename="/2024/03/22/14/middle_2542x2738-143514_v3_12201711089314426_0977dcd7d4a5a6a8140dc5feae1c7a96.jpg"
>                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
>         </div>
>         <div><br></div>
>         <div>第三家喝了熊煮咖啡。主理人是世界咖啡冲煮大赛的获奖选手，必须来杯手冲。爱我中华，选了云南的豆，是我喜欢的口味。</div>
>         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4096x2393-143518_v3_16871711089318560_136209cd04576230c869ff66662cd572.jpg"
>                         data-filename="/2024/03/22/14/middle_4096x2393-143518_v3_16871711089318560_136209cd04576230c869ff66662cd572.jpg"
>                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
>         </div>
>         <div><br></div>
>         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_3406x5118-143535_v3_18731711089337968_26a405c554b985d3ef33e9f07bce2717.jpg"
>                         data-filename="/2024/03/22/14/middle_3406x5118-143535_v3_18731711089337968_26a405c554b985d3ef33e9f07bce2717.jpg"
>                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
>         </div>
>         <div><br></div>
>         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_3010x3419-143514_v3_17111711089314289_9a7d524e4dd6d48d1797648e563513f8.jpg"
>                         data-filename="/2024/03/22/14/middle_3010x3419-143514_v3_17111711089314289_9a7d524e4dd6d48d1797648e563513f8.jpg"
>                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
>         </div>
>         <div><br></div>
>         <div>蹭拍一张小伙伴买的方象咖啡，颜值挺高。<img
>                         src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_3479x2359-143515_v3_13401711089315275_3700ae692f054be7677ee281af930caa.jpg"
>                         data-filename="/2024/03/22/14/middle_3479x2359-143515_v3_13401711089315275_3700ae692f054be7677ee281af930caa.jpg"
>                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
>         </div>
>         <div><br></div>
>         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2268x3024-143519_v3_10921711089319424_6f693d390a2469419847ef420319fdaf.jpg"
>                         data-filename="/2024/03/22/14/middle_2268x3024-143519_v3_10921711089319424_6f693d390a2469419847ef420319fdaf.jpg"
>                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
>         </div>
>         <div><br></div>
>         <div>另外还有贵州的咖啡旅人（刺梨咖啡很有兴趣）、北京的隐咖啡（深烘咖啡专门店，苦的很有礼貌）、大连的车轮子咖啡（微醺小车轮看着不错）等等，实在喝不过来了，周末再去试试。<br></div>
> </div>
> ```
> 
> 下面错误日志： ![FaultLog](https://private-user-images.githubusercontent.com/93482443/317169327-f146518d-dd04-460f-a674-6584bc709b9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjYzOTEsIm5iZiI6MTcxMTUyNjA5MSwicGF0aCI6Ii85MzQ4MjQ0My8zMTcxNjkzMjctZjE0NjUxOGQtZGQwNC00NjBmLWE2NzQtNjU4NGJjNzA5YjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA3NTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNzliZmJmOWYwYWIyNmYwYTE3ZGM4ZTY2OGNkNWIwYTM1YjBlYTc0Y2ZkZmQ0MTg1MDRmYmM0ZjMyMDFjMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NubqnIf3hwySgSu3E39xM4-dRyZ4oYgWH7Dbu4DM3so)

我试下~

**Comment by 0xmou** [comment]
> > 解析的文本：
> > ```
> > <div class="view-fullmodle"> <a class="confirm-btn mb10" ttname="bbs_detail_onlylzpic"
> >                 href="https://jiaxing.19lou.com/creampic-fid-779-t-97041711089344239-p-97731711089344480-nodigest-all-dateline.html"><span>只看楼主大图</span></a>
> > </div>
> > <div>
> >         <div>今天是南湖天地咖啡节第一天，中午就跟小伙伴噶闹忙去了。今年品牌明显多了，一时都不知道应该喝哪几家，随意感受了一下。<br><br>先说，不爱咖啡的小伙伴谨慎冲。场地很小，人超多，人气旺的摊位都要排队。价格不便宜，一般都是38-48元的价位。<br><br>第一家喝了云南的谙客咖啡，这家去年就在。还记得去年我喝的是“有风在大理”，去年要68元，今年还有，只要48元了，伤心。今年的新品是“繁花”，依然是68元。节省的我选了非新品“菇的咖啡”，48元，大致是菌菇风味的底+朗姆酒+啤酒花的沫，整体野生菌味很明显，我挺爱的，但是我的小伙伴们没一个爱菇味。买一杯咖啡，就送了包包和贴纸，好感度拉满。<img
> >                         src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2852x2363-143517_v3_12591711089317660_6c54216859ffc3fd36822ac28584b420.jpg"
> >                         data-filename="/2024/03/22/14/middle_2852x2363-143517_v3_12591711089317660_6c54216859ffc3fd36822ac28584b420.jpg"
> >                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
> >         </div>
> >         <div><br></div>
> >         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2700x3012-143517_v3_17451711089318007_c776635789c2912a64c34bfdc0d7d516.jpg"
> >                         data-filename="/2024/03/22/14/middle_2700x3012-143517_v3_17451711089318007_c776635789c2912a64c34bfdc0d7d516.jpg"
> >                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
> >         </div>
> >         <div><br></div>
> >         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4096x5461-143536_v3_20191711089341180_f63d670a1adef88fca9934bea4f6d92f.jpg"
> >                         data-filename="/2024/03/22/14/middle_4096x5461-143536_v3_20191711089341180_f63d670a1adef88fca9934bea4f6d92f.jpg"
> >                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
> >         </div>
> >         <div><br></div>
> >         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4032x3024-143518_v3_12281711089318759_50040f301f3e70a67ca670916be22f6f.jpg"
> >                         data-filename="/2024/03/22/14/middle_4032x3024-143518_v3_12281711089318759_50040f301f3e70a67ca670916be22f6f.jpg"
> >                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
> >         </div>
> >         <div><br>第二家喝了广州的&amp;U。我们人多，把“黑色森林”、“柏林少女”、“荔城挂绿”、“花园派对”都点了。个人口味比较喜欢黑色森林（液体巧克力蛋糕味）和荔城挂绿（很清爽）。</div>
> >         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4096x3483-143522_v3_17951711089322833_508c0acfee35f996fdf9fb7c0cf43d72.jpg"
> >                         data-filename="/2024/03/22/14/middle_4096x3483-143522_v3_17951711089322833_508c0acfee35f996fdf9fb7c0cf43d72.jpg"
> >                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
> >         </div>
> >         <div><br></div>
> >         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2542x2738-143514_v3_12201711089314426_0977dcd7d4a5a6a8140dc5feae1c7a96.jpg"
> >                         data-filename="/2024/03/22/14/middle_2542x2738-143514_v3_12201711089314426_0977dcd7d4a5a6a8140dc5feae1c7a96.jpg"
> >                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
> >         </div>
> >         <div><br></div>
> >         <div>第三家喝了熊煮咖啡。主理人是世界咖啡冲煮大赛的获奖选手，必须来杯手冲。爱我中华，选了云南的豆，是我喜欢的口味。</div>
> >         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_4096x2393-143518_v3_16871711089318560_136209cd04576230c869ff66662cd572.jpg"
> >                         data-filename="/2024/03/22/14/middle_4096x2393-143518_v3_16871711089318560_136209cd04576230c869ff66662cd572.jpg"
> >                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
> >         </div>
> >         <div><br></div>
> >         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_3406x5118-143535_v3_18731711089337968_26a405c554b985d3ef33e9f07bce2717.jpg"
> >                         data-filename="/2024/03/22/14/middle_3406x5118-143535_v3_18731711089337968_26a405c554b985d3ef33e9f07bce2717.jpg"
> >                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
> >         </div>
> >         <div><br></div>
> >         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_3010x3419-143514_v3_17111711089314289_9a7d524e4dd6d48d1797648e563513f8.jpg"
> >                         data-filename="/2024/03/22/14/middle_3010x3419-143514_v3_17111711089314289_9a7d524e4dd6d48d1797648e563513f8.jpg"
> >                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
> >         </div>
> >         <div><br></div>
> >         <div>蹭拍一张小伙伴买的方象咖啡，颜值挺高。<img
> >                         src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_3479x2359-143515_v3_13401711089315275_3700ae692f054be7677ee281af930caa.jpg"
> >                         data-filename="/2024/03/22/14/middle_3479x2359-143515_v3_13401711089315275_3700ae692f054be7677ee281af930caa.jpg"
> >                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
> >         </div>
> >         <div><br></div>
> >         <div><img src="https://att2.citysbs.com/jiaxing/2024/03/22/14/middle_2268x3024-143519_v3_10921711089319424_6f693d390a2469419847ef420319fdaf.jpg"
> >                         data-filename="/2024/03/22/14/middle_2268x3024-143519_v3_10921711089319424_6f693d390a2469419847ef420319fdaf.jpg"
> >                         data-source="attach" border="0" alt="南湖天地咖啡节噶闹忙 各种特调和手冲多的喝不过来" referrerpolicy="no-referrer">
> >         </div>
> >         <div><br></div>
> >         <div>另外还有贵州的咖啡旅人（刺梨咖啡很有兴趣）、北京的隐咖啡（深烘咖啡专门店，苦的很有礼貌）、大连的车轮子咖啡（微醺小车轮看着不错）等等，实在喝不过来了，周末再去试试。<br></div>
> > </div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 下面错误日志： ![FaultLog](https://private-user-images.githubusercontent.com/93482443/317169327-f146518d-dd04-460f-a674-6584bc709b9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjkyNjksIm5iZiI6MTcxMTUyODk2OSwicGF0aCI6Ii85MzQ4MjQ0My8zMTcxNjkzMjctZjE0NjUxOGQtZGQwNC00NjBmLWE2NzQtNjU4NGJjNzA5YjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA4NDI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YjA0NjM2MjhlYWNlMmZlMjUwOWQ1NDA4NmY5ZjFhYWIyZDEzNmEyNmNjMDhmNzNjNmYwNmM4M2IzZjVlODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i-30uU1mUt9I7NZsLcjLjskpFrWw6NepGJHQJoWCUWA)
> 
> ![image](https://private-user-images.githubusercontent.com/27256120/317198828-fb20bf97-0a2d-4084-af7e-ab214a58d79c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzEyNjMsIm5iZiI6MTcxMTUzMDk2MywicGF0aCI6Ii8yNzI1NjEyMC8zMTcxOTg4MjgtZmIyMGJmOTctMGEyZC00MDg0LWFmN2UtYWIyMTRhNThkNzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NDViNWM1OWM5MDIxMmY2YmZkNDM2YjkwNWYzODFmYzEwZjQzYjAyYzY3MTAzNTRhM2QwNmNiYjQ3NjExODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vf8iCBHr4flWmskbzGsU7QcUg4bXSumPFMZZln_hyeE) 临时方案：可以先将嵌套的这个div删除一下； 长期方案：优化一下嵌套渲染

OK，我试一下

**Comment by asasugar** [comment]
@0xmou 后续版本我会优化一下这个问题

**Comment by asasugar** [comment]
> @0xmou 后续版本我会优化一下这个问题

v1.0.2 版本已优化， https://github.com/asasugar/HPRichText/releases/tag/v1.0.2

**Comment by 0xmou** [comment]
> > @0xmou 后续版本我会优化一下这个问题
> 
> v1.0.2 版本已优化

OKOK，非常感谢 😃  😉

**Comment by asasugar** [comment]
> > > @0xmou 后续版本我会优化一下这个问题
> > 
> > 
> > v1.0.2 版本已优化
> 
> OKOK，非常感谢 😃 😉

包还在审核ing，后续审核过了可以更新一下
