### ISSUE TITLE
内容样式如何调整

### ISSUE THREAD

**Issue by maohongshan** [asasugar/HPRichText#20]
内容的字体、字号、行间距、字间距这些如何调整啊

**Comment by asasugar** [comment]
> 内容的字体、字号、行间距、字间距这些如何调整啊

参考示例：https://github.com/asasugar/HPRichText/blob/v1.0.8/entry/src/main/ets/pages/Example_4.ets

关于`line-height`属性，v1.0.8版本已修复问题，详见https://github.com/asasugar/HPRichText/commit/ce785d89ba89c8b17cb56e839d7885f93b8973f6
