### ISSUE TITLE
writing-mode: vertical-lr文字竖排不支持

### ISSUE THREAD

**Issue by zqsong** [asasugar/HPRichText#25]
如题，writing-mode: vertical-lr不生效

**Comment by asasugar** [comment]
![image](https://github.com/user-attachments/assets/2568dc04-41ce-4130-b237-2991c5789f53)
v2.0.1版本对这四个值做竖直方向的处理，处理过程参考：https://developer.huawei.com/consumer/cn/doc/harmonyos-faqs-V5/faqs-arkui-91-V5
