### ISSUE TITLE
HPRichText整体点击事件无响应

### ISSUE THREAD

**Issue by duaiyun1314** [asasugar/HPRichText#26]
点击事件被普通的text标签拦截，且没有开放出回调，导致点击非a标签的文本无反应
![Uploading WX20240715-132534.png…]()

**Comment by duaiyun1314** [comment]
/**
   * @description: Span文本样式构造器
   * @returns {*}
   */
  @Builder
  textBuilder($$: TextBuilderOptions) {
    Span($$.node.text)
      .fancySpan($$.parentNode?.artUIStyleObject)
      .onClick(() => {
        if ($$.parentNode?.tag !== 'a') return;

        // a标签增加回调事件
        try {
          this.onLinkPress?.({ text: $$.node.text, link: $$.parentNode?.attr?.href });
        } catch (error) {
          console.error(`ErrorCode: ${error.code},  Message: ${error.message}`);
        }
      })
  }

**Comment by asasugar** [comment]
> /**
> 
> * @description: Span文本样式构造器
> * @returns {*}
>   */
>   @builder
>   textBuilder($$: TextBuilderOptions) {
>   Span($$.node.text)
>   .fancySpan($$.parentNode?.artUIStyleObject)
>   .onClick(() => {
>   if ($$.parentNode?.tag !== 'a') return;
>   // a标签增加回调事件
>   try {
>   this.onLinkPress?.({ text: .node.text,link:.parentNode?.attr?.href });
>   } catch (error) {
>   console.error(`ErrorCode: ${error.code},  Message: ${error.message}`);
>   }
>   })
>   }

之前是考虑到增加其他标签的点击事件的话，需要去解析script标签下的事件去匹配。现在想了一下可以暴露事件回调给你，然后你那边在根据当前已有的信息去处理事件

**Comment by asasugar** [comment]
<img width="979" alt="image" src="https://github.com/user-attachments/assets/06a6922f-7c05-4f20-a192-f16ec6fb9021">
<img width="506" alt="image" src="https://github.com/user-attachments/assets/e70a5c44-fd27-4242-b4ad-181bf37e69f8">
需要使用方根据返回的eventFnName去处理点击事件
