### ISSUE TITLE
能看下为啥这段文本的空格\t被忽略了吗

### ISSUE THREAD

**Issue by yollet** [asasugar/HPRichText#28]
<p>\t<p class="MsoNormal" style="text-indent:21pt;">\t\t<span style="font-family:宋体;font-size:14pt;font-weight:normal;">反馈回来发货了护林防火撒flash发拉萨<span>3</span><span>减肥啦设计费拉数据发啦</span><span>21983u198319</span><span>放假啊射流风机阿拉善飞机啊失蜡法积极我</span><span>APP</span><span>巨垃圾管理；加了阿济格刚才那，把你拉许嵩 </span></span><span style="font-family:宋体;font-size:14pt;font-weight:normal;"></span>	</p>\t\t<p class="MsoNormal" style="text-indent:21pt;">		<span style="font-family:宋体;font-size:14pt;font-weight:normal;">你电脑飞鹅岭分动箱色<span>24</span><span>手打挖方</span><span>2の342242</span><span>打撒福娃；防磨瓦</span></span><span style="font-family:宋体;font-size:14pt;font-weight:normal;"></span>	</p></p>

**Comment by yollet** [comment]
`<p>\t<p class="MsoNormal" style="text-indent:21pt;">\t\t<span style="font-family:宋体;font-size:14pt;font-weight:normal;">反馈回来发货了护林防火撒flash发拉萨<span>3</span><span>减肥啦设计费拉数据发啦</span><span>21983u198319</span><span>放假啊射流风机阿拉善飞机啊失蜡法积极我</span><span>APP</span><span>巨垃圾管理；加了阿济格刚才那，把你拉许嵩 </span></span><span style="font-family:宋体;font-size:14pt;font-weight:normal;"></span>	</p>\t<p class="MsoNormal" style="text-indent:21pt;">\t\t<span style="font-family:宋体;font-size:14pt;font-weight:normal;">你电脑飞鹅岭分动箱色<span>24</span><span>手打挖方</span><span>2の342242</span><span>打撒福娃；防磨瓦</span></span><span style="font-family:宋体;font-size:14pt;font-weight:normal;"></span>	</p></p>`

**Comment by asasugar** [comment]
> `<p>\t<p class="MsoNormal" style="text-indent:21pt;">\t\t<span style="font-family:宋体;font-size:14pt;font-weight:normal;">反馈回来发货了护林防火撒flash发拉萨<span>3</span><span>减肥啦设计费拉数据发啦</span><span>21983u198319</span><span>放假啊射流风机阿拉善飞机啊失蜡法积极我</span><span>APP</span><span>巨垃圾管理；加了阿济格刚才那，把你拉许嵩 </span></span><span style="font-family:宋体;font-size:14pt;font-weight:normal;"></span> </p>\t<p class="MsoNormal" style="text-indent:21pt;">\t\t<span style="font-family:宋体;font-size:14pt;font-weight:normal;">你电脑飞鹅岭分动箱色<span>24</span><span>手打挖方</span><span>2の342242</span><span>打撒福娃；防磨瓦</span></span><span style="font-family:宋体;font-size:14pt;font-weight:normal;"></span> </p></p>`

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/9108f675-b671-4a78-87a0-d10c3b90ed97">

**Comment by yollet** [comment]
预想的效果应该是首行有空格，我把\t  replaceAll成’_‘是能正常显示在首行前面的。。
![WX20240723-103652@2x](https://github.com/user-attachments/assets/ca2f36b7-0dce-499a-b7c3-b7f62d6719ef)
![Uploading WX20240723-104029@2x.png…]()

**Comment by asasugar** [comment]
贴一下想要的效果呗，我对比一下

**Comment by yollet** [comment]
![WX20240723-104029@2x](https://github.com/user-attachments/assets/04a04717-9e92-4b8c-9185-71cb3b51f26e)
就这个 把_换成空格的样子

**Comment by asasugar** [comment]
v2.1.0会修复，且需要将字符串改为:

```js
    <p><p class="MsoNormal" style="text-indent:21pt;"><span style="font-family:宋体;font-size:14pt;font-weight:normal;">\t\t\t反馈回来发货了护林防火撒flash发拉萨<span>3</span><span>减肥啦设计费拉数据发啦</span><span>21983u198319</span><span>放假啊射流风机阿拉善飞机啊失蜡法积极我</span><span>APP</span><span>巨垃圾管理；加了阿济格刚才那，把你拉许嵩 </span></span><span style="font-family:宋体;font-size:14pt;font-weight:normal;"></span>	</p><p class="MsoNormal" style="text-indent:21pt;"><span style="font-family:宋体;font-size:14pt;font-weight:normal;">\t\t\t你电脑飞鹅岭分动箱色<span>24</span><span>手打挖方</span><span>2の342242</span><span>打撒福娃；防磨瓦</span></span><span style="font-family:宋体;font-size:14pt;font-weight:normal;"></span>	</p></p>

```
