### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ZhongYangdev** [asasugar/HPRichText#3]
我的项目是api9的。引入组建后，运行项目报错。请问是什么原因呢？
![image](https://github.com/asasugar/HPRichText/assets/63274531/a9922080-0df2-4b00-8ed1-6d9105ac94aa)

**Comment by ZhongYangdev** [comment]
貌似是与这里的配置冲突了
![image](https://github.com/asasugar/HPRichText/assets/63274531/d47299ae-c5b2-4934-874e-e7297814f143)

**Comment by asasugar** [comment]
https://github.com/asasugar/HPRichText/tree/v1.0.0 这个分支是基于api 9
