### ISSUE TITLE
部分场景解析富文本生成的结构不正确

### ISSUE THREAD

**Issue by WeiYuanlin** [asasugar/HPRichText#30]
一下是html代码
```html
<p>选项11111111<br /><img src="https://mgl-img-test.mageline-mall.cn/image/742a9fe7-a080-4622-b77f-6d0958c8e131.jpeg" alt="" width="150" height="150" /><img src="https://mgl-img-test.mageline-mall.cn/image/74f151a1-a2cb-4616-a941-e733e95fcfa0.jpeg" alt="" width="180" height="180" /><img src="https://mgl-img-test.mageline-mall.cn/image/847c27e2-ffc6-425b-81e5-775f8da2b314.gif" alt="" width="161" height="161" /><br />lalalalalalallalalalallalalala</p>

```
对应的web效果dom结构如下：
![image](https://github.com/user-attachments/assets/1b4aa821-5b52-4185-927c-4f8ef26bd995)

鸿蒙的arkUI 实际结构如下：
![image](https://github.com/user-attachments/assets/dcbdfe3b-0598-49a0-804c-1481085e627e)

html代码实际上是3个连续img标签，但是生成富文本结构第一个img标签被分割出去了

**Comment by CodeSlaveZhang** [comment]
我建议用styledString来做。image用customSpan做，可以自定义每个image的位置。

**Comment by asasugar** [comment]
> 我建议用styledString来做。image用customSpan做，可以自定义每个image的位置。

后续根据 12 版本api优化改进
