### ISSUE TITLE
background-color不生效

### ISSUE THREAD

**Issue by DamonChen117** [asasugar/HPRichText#32]
背景还是白色的：
 "@ohasasugar/hp-richtext": "^2.1.0"
`'<span style="background-color:yellow;color:black">your</span>'`

**Comment by asasugar** [comment]
> 背景还是白色的： "@ohasasugar/hp-richtext": "^2.1.0" `'<span style="background-color:yellow;color:black">your</span>'`

其实是支持的，你用个十六进制的颜色就行`#ccc`，我会新增一下非十六进制的兼容
