### ISSUE TITLE
下面这段富文本的 <strong style='font-size:13px;color=#808080;'><font color='#1a1a1a'> 秃头了 <\font><\strong> 加粗不起作用

### ISSUE THREAD

**Issue by ycbiao** [asasugar/HPRichText#33]
`<font style='font-size:13px;color=#808080;' color='#808080'>请上传测试为 <\font><strong style='font-size:13px;color=#808080;'><font color='#1a1a1a'> 秃头了 <\font><\strong><font color='#808080' style='font-size:13px;color=#808080;'> 的查宿舍<\font><br><font style='font-size:13px;color=#808080;' color='#808080'>联系电话 <\font><strong style='font-size:13px;color=#808080;'><font color='#1a1a1a'> 18123434555 <\font><\strong>`

**Comment by ycbiao** [comment]
![image](https://github.com/user-attachments/assets/8bd009e1-86ee-4ea6-86d9-bf00bf3e206f)
这里改成600就可以

**Comment by asasugar** [comment]
> `<font style='font-size:13px;color=#808080;' color='#808080'>请上传测试为 <\font><strong style='font-size:13px;color=#808080;'><font color='#1a1a1a'> 秃头了 <\font><\strong><font color='#808080' style='font-size:13px;color=#808080;'> 的查宿舍<\font><br><font style='font-size:13px;color=#808080;' color='#808080'>联系电话 <\font><strong style='font-size:13px;color=#808080;'><font color='#1a1a1a'> 18123434555 <\font><\strong>`

    <font style='font-size:13px;color=#808080;' color='#808080'>请上传测试为 </font><strong style='font-size:13px;color=#808080;'><font color='#1a1a1a'> 秃头了 </font></strong><font color='#808080' style='font-size:13px;color=#808080;'> 的查宿舍</font><br><font style='font-size:13px;color=#808080;' color='#808080'>联系电话 </font><strong style='font-size:13px;color=#808080;'><font color='#1a1a1a'> 18123434555 </font></strong>


闭合标签是`/`，不是`\`
