### ISSUE TITLE
<b>标签加粗不生效

### ISSUE THREAD

**Issue by zwjnb** [asasugar/HPRichText#34]
<b>标签使用bold加粗效果不生效，麻烦优化下

**Comment by asasugar** [comment]
![Uploading image.png…]()

**Comment by asasugar** [comment]
> 标签使用bold加粗效果不生效，麻烦优化下

<img width="844" alt="image" src="https://github.com/user-attachments/assets/38023ec8-7494-416d-bd42-b400ce603507">
