### ISSUE TITLE
onLinkPress会导致想点击整个组件没办法回调

### ISSUE THREAD

**Issue by ycbiao** [asasugar/HPRichText#35]
![image](https://github.com/user-attachments/assets/687d86b4-7296-4b8d-9c69-4f7b9e949742)

**Comment by asasugar** [comment]
> ![image](https://private-user-images.githubusercontent.com/11884909/354173070-687d86b4-7296-4b8d-9c69-4f7b9e949742.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjM3NzcsIm5iZiI6MTcyMjkyMzQ3NywicGF0aCI6Ii8xMTg4NDkwOS8zNTQxNzMwNzAtNjg3ZDg2YjQtNzI5Ni00YjhkLTljNjktNGY3YjllOTQ5NzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA1NTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MzJjMGM3OTIyZjUyNTFiMDg4YTQ3NjNhNGU3ZGFhYTViYjdjMzcxNWIzMTM4NTVmMjcwMDA5MmIxMGQ5OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.583HlqZK7JOmp4SJcCZ2PvaX9roImKb0y7idArRLNf0)

```ts
HPRichText({
        richTextOption: $richTextOption,
        needScroll: true,
        onLinkPress: (e) => {
          return e;
        }
      })
        .onTouch((event) => {
          if ((event as TouchEvent).type == TouchType.Down) {
            console.info('stack touched type: ' + (event as TouchEvent).type)
          }
        })
```

**Comment by hejinxigege** [comment]
在列表中怎么解决这个问题

**Comment by asasugar** [comment]
> 在列表中怎么解决这个问题

import { HPRichTextV2, RichTextOptionModelV2 } from '@ohasasugar/hp-richtext';

@Entry
@Component
struct Index {
  @State arr: RichTextOptionModelV2[] = []

  // 模拟请求接口数据
  aboutToAppear(): void {
    for (let i = 0; i < 4; i++) {
      let o = new RichTextOptionModelV2();
      o.richTextOption.content = `<span style="color: #fff">我是 HPRichTextV2 组件${i}</span>`;
      this.arr.push(o)
    }
  }

  build() {
    Column() {
      List({ space: 10 }) {
        ForEach(this.arr, (item: RichTextOptionModelV2) => {
          ListItem() {
            HPRichTextV2({
              richTextModel: item
            })
              .width('100%')
              .height(100)
              .borderRadius(10)
              .backgroundColor(0x007DFF)
              .onClick((event) => {
                console.log('1111', JSON.stringify(item), JSON.stringify(event))
              })
          }
        }, (item: number) => JSON.stringify(item))
      }
    }
    .padding(12)
    .height('100%')
    .backgroundColor(0xF1F3F5)
  }
}
