### ISSUE TITLE
建议新增居中选项

### ISSUE THREAD

**Issue by badboy-tian** [asasugar/HPRichText#37]
您好, 请问可以新增居中选项吗?  谢谢`
<img width="327" alt="image" src="https://github.com/user-attachments/assets/b83cd077-6452-4499-b7b8-7f65d23fccf9">

**Comment by badboy-tian** [comment]
用constraintSize代替

**Comment by asasugar** [comment]
提供一下需要渲染的字符串

**Comment by badboy-tian** [comment]
```
"您好, 现在会员促销期间<font color='red'>打6折</font>哟~错过时间恢复原价哈!"
```

```
import { HPRichText, RichTextOption } from '@ohasasugar/hp-richtext'
import { WebUrlItem } from '../../../pages/common/WebViewPage';
import { Pages } from '../../../pages/Pages';
import { black, black90, themeColor } from '../../common';
import { getStrFromRes } from '../../tools';

@CustomDialog
export struct MyConfirmDialog {
  @Consume("NavPathStack") pathStack?: NavPathStack;
  title: string | Resource = '我是标题'
  content: string | Resource = "我是内容"
  positiveText: string | Resource = "确定"
  negativeText: string | Resource = "取消"
  onPositiveClick?: () => void;
  onNegativeClick?: () => void;
  controller: CustomDialogController = new CustomDialogController({
    builder: MyConfirmDialog({}),
  })
  @State richTextOption: RichTextOption = {
    content: '',
  }

  async aboutToAppear(): Promise<void> {
    this.richTextOption = {
      content: (typeof this.content === 'string' ? this.content : await getStrFromRes(this.content)),
      baseFontSize: 15,
      baseFontColor: "#99000000"
    }
  }

  build() {
    Column() {
      Stack() {
        Text(this.title).fontSize(17)
        //Image($r('app.media.et_delete')).width(22).aspectRatio(1).position({ right: 5, top: 5 })
      }.height(45).width("100%").margin({ top: 5 })

      HPRichText({
        richTextOption: $richTextOption, needScroll: true, onLinkPress: (url) => {
          this.pathStack?.pushPathByName(Pages.WebViewPage, WebUrlItem.getUrlItem(url.link, $r('app.string.web_title')))
          return url
        }
      }).padding({
        left: 18,
        right: 18,
        top: 10,
        bottom: 15
      }).width("100%").align(Alignment.Center).constraintSize({
        minHeight: 88
      })

      Column({ space: 18 }) {
        Row() {
          Button(this.positiveText === "确定" ? $r('app.string.dialog_sure') : this.positiveText,
            { type: ButtonType.Normal })
            .height(44)
            .fontColor(Color.White)
            .fontSize(14)
            .fontWeight(FontWeight.Normal)
            .borderRadius(6)
            .layoutWeight(1)
            .backgroundColor(themeColor)
            .onClick(() => {
              if (this.onPositiveClick) {
                this.onPositiveClick()
              }

              this.controller.close()
            })
        }

        Row() {
          Button(this.negativeText === "取消" ? $r('app.string.dialog_cancel') : this.negativeText,
            { type: ButtonType.Normal })
            .height(44)
            .fontSize(14)
            .fontColor(black)
            .fontWeight(FontWeight.Normal)
            .borderWidth(1)
            .borderColor(themeColor)
            .borderRadius(6)
            .layoutWeight(0.6)
            .backgroundColor(Color.White)
            .onClick(() => {
              if (this.onNegativeClick) {
                this.onNegativeClick()
              }

              this.controller.close()
            })
        }
      }.padding({
        left: 20,
        right: 20
      }).width("100%")
      .margin({
        bottom: 22
      })
    }.width("100%")
  }
}
```

**Comment by asasugar** [comment]
> ```
> "您好, 现在会员促销期间<font color='red'>打6折</font>哟~错过时间恢复原价哈!"
> ```
> 
> ```
> import { HPRichText, RichTextOption } from '@ohasasugar/hp-richtext'
> import { WebUrlItem } from '../../../pages/common/WebViewPage';
> import { Pages } from '../../../pages/Pages';
> import { black, black90, themeColor } from '../../common';
> import { getStrFromRes } from '../../tools';
> 
> @CustomDialog
> export struct MyConfirmDialog {
>   @Consume("NavPathStack") pathStack?: NavPathStack;
>   title: string | Resource = '我是标题'
>   content: string | Resource = "我是内容"
>   positiveText: string | Resource = "确定"
>   negativeText: string | Resource = "取消"
>   onPositiveClick?: () => void;
>   onNegativeClick?: () => void;
>   controller: CustomDialogController = new CustomDialogController({
>     builder: MyConfirmDialog({}),
>   })
>   @State richTextOption: RichTextOption = {
>     content: '',
>   }
> 
>   async aboutToAppear(): Promise<void> {
>     this.richTextOption = {
>       content: (typeof this.content === 'string' ? this.content : await getStrFromRes(this.content)),
>       baseFontSize: 15,
>       baseFontColor: "#99000000"
>     }
>   }
> 
>   build() {
>     Column() {
>       Stack() {
>         Text(this.title).fontSize(17)
>         //Image($r('app.media.et_delete')).width(22).aspectRatio(1).position({ right: 5, top: 5 })
>       }.height(45).width("100%").margin({ top: 5 })
> 
>       HPRichText({
>         richTextOption: $richTextOption, needScroll: true, onLinkPress: (url) => {
>           this.pathStack?.pushPathByName(Pages.WebViewPage, WebUrlItem.getUrlItem(url.link, $r('app.string.web_title')))
>           return url
>         }
>       }).padding({
>         left: 18,
>         right: 18,
>         top: 10,
>         bottom: 15
>       }).width("100%").align(Alignment.Center).constraintSize({
>         minHeight: 88
>       })
> 
>       Column({ space: 18 }) {
>         Row() {
>           Button(this.positiveText === "确定" ? $r('app.string.dialog_sure') : this.positiveText,
>             { type: ButtonType.Normal })
>             .height(44)
>             .fontColor(Color.White)
>             .fontSize(14)
>             .fontWeight(FontWeight.Normal)
>             .borderRadius(6)
>             .layoutWeight(1)
>             .backgroundColor(themeColor)
>             .onClick(() => {
>               if (this.onPositiveClick) {
>                 this.onPositiveClick()
>               }
> 
>               this.controller.close()
>             })
>         }
> 
>         Row() {
>           Button(this.negativeText === "取消" ? $r('app.string.dialog_cancel') : this.negativeText,
>             { type: ButtonType.Normal })
>             .height(44)
>             .fontSize(14)
>             .fontColor(black)
>             .fontWeight(FontWeight.Normal)
>             .borderWidth(1)
>             .borderColor(themeColor)
>             .borderRadius(6)
>             .layoutWeight(0.6)
>             .backgroundColor(Color.White)
>             .onClick(() => {
>               if (this.onNegativeClick) {
>                 this.onNegativeClick()
>               }
> 
>               this.controller.close()
>             })
>         }
>       }.padding({
>         left: 20,
>         right: 20
>       }).width("100%")
>       .margin({
>         bottom: 22
>       })
>     }.width("100%")
>   }
> }
> ```

接口返回的 content值发一下～

**Comment by badboy-tian** [comment]
哪个接口呀

**Comment by badboy-tian** [comment]
![image](https://github.com/user-attachments/assets/15ef7109-120f-46fb-b7a2-7bfb77c2db43)

**Comment by badboy-tian** [comment]
就是这样 也没有居中显示  也没有渲染对

**Comment by asasugar** [comment]
<img width="757" alt="image" src="https://github.com/user-attachments/assets/d2e6ee72-f947-43f2-acb1-131779b0eb15">
getStrFromRes执行之后返回的string值贴一下，谢谢

**Comment by badboy-tian** [comment]
我直接传的string, 没有传Resource
```
export function getStrFromRes(resource: Resource): Promise<string> {
  let resMgr = getContext().resourceManager
  let resId = resource.id
  return resMgr.getStringValue(resId)
}
```

**Comment by badboy-tian** [comment]
```
TDialogUtil.showConfirm({
              title: "退出提示",
              content: "您好, 现在会员促销期间<font color='red'>打6折</font>哟~错过时间恢复原价哈!",
              okMsg: "坚决退出",
              noMsg: "再考虑下",
              onOK: () => {
                this.pathStack?.pop()
              },
            })
```

**Comment by badboy-tian** [comment]
```
async aboutToAppear(): Promise<void> {
    this.richTextOption = {
      content: (typeof this.content === 'string' ? this.content : await getStrFromRes(this.content)),
      baseFontSize: 15,
      baseFontColor: "#99000000"
    }


    logE(this.richTextOption.content)
  }
```
打印出来是这样的
```
"您好, 现在会员促销期间<font color='red'>打6折</font>哟~错过时间恢复原价哈!"
```

**Comment by asasugar** [comment]
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/cc876d13-9d6d-437b-a0a7-13c76ffb7bba">
关于这个问题有以下两点：

1. v2.2.1版本会处理text-align传递过来的属性转化成鸿蒙下的 TextAlign枚举；
2. 你需要给你的html字符串添加一个`text-align: center`，如上图所示

**Comment by badboy-tian** [comment]
好的  期待v2.2.1
