### ISSUE TITLE
能不能支持web组件src网址传输，还有使用组件时长按没有菜单出现能优化一下，可以提供菜单吗

### ISSUE THREAD

**Issue by pansida** [asasugar/HPRichText#39]

**Comment by asasugar** [comment]
列举一下具体的标签跟api或者代码

**Comment by pansida** [comment]
![image](https://github.com/user-attachments/assets/b5255d6d-2341-4916-b3a5-bf010e3619e2)
上面是内部的richtext组件，使用HPRichText提供的这个组件长按没有复制一些的出现

**Comment by asasugar** [comment]
src传入网址的话本质就还是用的webview组件渲染了，那你这种场景可以直接用官方的 RichText组件即可
