### ISSUE TITLE
能不能把解析的dom结构在你渲染前整个回调或者插槽的形式开放出来，由使用者自定义对应类型的渲染组件？

### ISSUE THREAD

**Issue by Chang-Chen** [asasugar/HPRichText#40]
能不能把解析的dom结构在你渲染前整个回调或者插槽的形式开放出来，由使用者自定义对应类型的渲染组件？

我目前有个需求是渲染试卷的，题目和答案都是富文本，需要自己去控制富文本的每个样式

**Comment by Chang-Chen** [comment]
![image](https://github.com/user-attachments/assets/19d04c8f-0198-40cd-a4b9-c3d7f75e0a14)
例如这样让开发者自定义实现需要的需求

**Comment by asasugar** [comment]
你指的是想要得到格式化之后的字符串？
例如：
<img width="1378" alt="image" src="https://github.com/user-attachments/assets/54a0887f-7b84-47c0-a1c9-5d36c58e6a1e">

**Comment by asasugar** [comment]
v2.2.2版本，新增导出 `HTMLParser`类，可输出格式化后的字符串数据；

```ts
import { HTMLParser, RichTextOption } from '@ohasasugar/hp-richtext';
...
const htmlParser = new HTMLParser(this.richTextOption);
this.htmlJson = htmlParser.html2json();
```
