### ISSUE TITLE
a标签后跟文本解析错误

### ISSUE THREAD

**Issue by duaiyun1314** [asasugar/HPRichText#43]
<div><a href='https://www.baidu.com'>点击我</a>我是后面的文本</div>
a标签在处理</a>后应该关闭a.tagType='inline'的属性，否则后面的文本也会加入到a标签里面

**Comment by asasugar** [comment]
> [点击我](https://www.baidu.com)我是后面的文本
> a标签在处理后应该关闭a.tagType='inline'的属性，否则后面的文本也会加入到a标签里面

v2.2.1版本已修复，审核中
