### ISSUE TITLE
升级到2.2.1闪退

### ISSUE THREAD

**Issue by hejinxigege** [asasugar/HPRichText#44]
这个是我加载的内容
<font color='#fe89c7'>宝宝</font><font color='#fe89c7'>不爱吃饭</font>别怕！有它轻松拿捏挑食<font color='#fe89c7'>宝宝</font>！我家<font color='#fe89c7'>宝宝</font>不知是随...#<font color='#fe89c7'>宝宝</font>营养补充#

    this.richTextOption = {
      baseFontSize: 17,
      baseFontColor: '#333333',
      content: "<font color='#fe89c7'>宝宝</font><font color='#fe89c7'>不爱吃饭</font>别怕！有它轻松拿捏挑食<font color='#fe89c7'>宝宝</font>！我家<font color='#fe89c7'>宝宝</font>不知是随...#<font color='#fe89c7'>宝宝</font>营养补充#"
    }

Error message:Cannot read property push of undefined
SourceCode:
                    firstNodes[firstNodesLength - 1].nodes.push(node);
                    ^
Stacktrace:
    at end (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/common/utils/html/html-parser.ts:405:11)
    at parseEndTag (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/common/utils/html/html-parser.ts:321:9)
    at html2json (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/common/utils/html/html-parser.ts:270:13)
    at onUpdateRichTextOption (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/components/hprichtext/HPRichText.ets:125:21)
    at aboutToAppear (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/components/hprichtext/HPRichText.ets:132:7)

**Comment by badboy-tian** [comment]
2.2.1不是还没上架吗

**Comment by asasugar** [comment]
> 这个是我加载的内容 宝宝不爱吃饭别怕！有它轻松拿捏挑食宝宝！我家宝宝不知是随...#宝宝营养补充#
> 
> ```
> this.richTextOption = {
>   baseFontSize: 17,
>   baseFontColor: '#333333',
>   content: "<font color='#fe89c7'>宝宝</font><font color='#fe89c7'>不爱吃饭</font>别怕！有它轻松拿捏挑食<font color='#fe89c7'>宝宝</font>！我家<font color='#fe89c7'>宝宝</font>不知是随...#<font color='#fe89c7'>宝宝</font>营养补充#"
> }
> ```
> 
> Error message:Cannot read property push of undefined SourceCode: firstNodes[firstNodesLength - 1].nodes.push(node); ^ Stacktrace: at end (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/common/utils/html/html-parser.ts:405:11) at parseEndTag (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/common/utils/html/html-parser.ts:321:9) at html2json (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/common/utils/html/html-parser.ts:270:13) at onUpdateRichTextOption (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/components/hprichtext/HPRichText.ets:125:21) at aboutToAppear (oh_modules/.ohpm/@ohasasugar+hp-richtext@2.2.0/oh_modules/@ohasasugar/hp-richtext/src/main/ets/components/hprichtext/HPRichText.ets:132:7)

![image](https://github.com/user-attachments/assets/14a6bd51-9d8f-4d65-935d-c71d1a204351)
清理一下缓存，从这看你是2.2.0版本

**Comment by asasugar** [comment]
<img width="286" alt="image" src="https://github.com/user-attachments/assets/005ded0c-d2be-4a3a-9e7b-070b4dad6a46">

**Comment by asasugar** [comment]
<img width="876" alt="image" src="https://github.com/user-attachments/assets/3a914799-2d49-469e-a493-828f29462cc2">

**Comment by hejinxigege** [comment]
好。我试试

**Comment by hejinxigege** [comment]
谢谢大佬
