### ISSUE TITLE
a标签后文字未继承外部布局样式

### ISSUE THREAD

**Issue by Er3c** [asasugar/HPRichText#46]
升级2.2.1之后 a标签可以跟后面的文字分开了，但是后面text的样式没有继承外层父布局的样式，文字大小不一样了
![image](https://github.com/user-attachments/assets/1b610a1e-7e86-4dbb-82fa-16599edaef09)
a标签外部跟着的text在该位置获取样式时是undefined，导致文字大小变成默认的了。

**Comment by asasugar** [comment]
升级到v2.2.3版本再试试。如未解决贴一下content传递的html字符串内容
