### ISSUE TITLE
如何对整体的HPRichText进行点击事件。

### ISSUE THREAD

**Issue by hejinxigege** [asasugar/HPRichText#48]
我做纯显示用。但是需要做整个控件的点击。做跳转需要
      HPRichText({
        richTextOption: $richTextOption,
        needScroll: false,
        onLinkPress: (e) => {
          return e;
        }
      }).onClick(() => {
        this.onItemClick()
      })

**Comment by asasugar** [comment]
参考[35](https://github.com/asasugar/HPRichText/issues/35)

**Comment by hejinxigege** [comment]
> 参考[35](https://github.com/asasugar/HPRichText/issues/35)

这样不行吧。在列表中滚动的话。手指很容易就触发了

**Comment by asasugar** [comment]
> > 参考[35](https://github.com/asasugar/HPRichText/issues/35)
> 
> 这样不行吧。在列表中滚动的话。手指很容易就触发了

你用onClick事件就行
