### ISSUE TITLE
是否支持文字底部绘制波浪线或带圆点，还有文字上标和下标呢

### ISSUE THREAD

**Issue by hfbi360** [asasugar/HPRichText#5]
能否实现文字底部绘制波浪线或带圆点，还有文字上标和下标呢？
<img width="91" alt="QQ20240409-092356@2x" src="https://github.com/asasugar/HPRichText/assets/1289896/e5d53abc-747e-4833-ab5e-c81a0a146e77">
![image2018-1-17 16_9_26](https://github.com/asasugar/HPRichText/assets/1289896/badb3a7f-8cce-462a-9334-0fe43316411b)
![image2018-1-17 16_9_54](https://github.com/asasugar/HPRichText/assets/1289896/7e1723ae-bc84-41dd-962a-d610f10e74a5)

**Comment by asasugar** [comment]
> 能否实现文字底部绘制波浪线或带圆点，还有文字上标和下标呢？ <img alt="QQ20240409-092356@2x" width="91" src="https://private-user-images.githubusercontent.com/1289896/320691929-e5d53abc-747e-4833-ab5e-c81a0a146e77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDQzMjIsIm5iZiI6MTcxMjY0NDAyMiwicGF0aCI6Ii8xMjg5ODk2LzMyMDY5MTkyOS1lNWQ1M2FiYy03NDdlLTQ4MzMtYWI1ZS1jODFhMGExNDZlNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDYyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTg1NzgwMTlmYmQ0MmE4ZmIyY2ZkZDJkMmNkMTM2YTdjZmQ2YjIxMjdlYzA1OGE2Y2M0ZmQ4NWVhYTQ0Y2FkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L440jRH-HDDdBaccjd64jr_3ic70yupQ94QWKf5pc-s"> ![image2018-1-17 16_9_26](https://private-user-images.githubusercontent.com/1289896/320691996-badb3a7f-8cce-462a-9334-0fe43316411b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDQzMjIsIm5iZiI6MTcxMjY0NDAyMiwicGF0aCI6Ii8xMjg5ODk2LzMyMDY5MTk5Ni1iYWRiM2E3Zi04Y2NlLTQ2MmEtOTMzNC0wZmU0MzMxNjQxMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDYyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNlOTBiNmRkMGRlODcxMmE4NTFlNDdmMjg0ZWY3ZDE1OWNkNDBiOTFhZWY5ZjUxOTkyMDJkNzFmMmY5ZDkwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R86iOFQ8h3xWIlJKg9fYY0Hd94Ut7XbPMVSMjXGdRXs) ![image2018-1-17 16_9_54](https://private-user-images.githubusercontent.com/1289896/320692014-7e1723ae-bc84-41dd-962a-d610f10e74a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDQzMjIsIm5iZiI6MTcxMjY0NDAyMiwicGF0aCI6Ii8xMjg5ODk2LzMyMDY5MjAxNC03ZTE3MjNhZS1iYzg0LTQxZGQtOTYyYS1kNjEwZjEwZTc0YTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDYyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTk3ZGI1NmI3Y2Y0NzI1YTIxODgxNjYyNjczMDIwMGRmMTdiOTI2MGM0YWM0ODNlZWRiZWI3OGUwZTAxMWRhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.C3cg9rXPGP4-nYbZykGyUjiWWFerMqE4IGBnXNNTqXw)

可以的，适配一下就行，可以贴一下你需要html的标签

**Comment by hfbi360** [comment]
> > 能否实现文字底部绘制波浪线或带圆点，还有文字上标和下标呢？ <img alt="QQ20240409-092356@2x" width="91" src="https://private-user-images.githubusercontent.com/1289896/320691929-e5d53abc-747e-4833-ab5e-c81a0a146e77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDQzMjIsIm5iZiI6MTcxMjY0NDAyMiwicGF0aCI6Ii8xMjg5ODk2LzMyMDY5MTkyOS1lNWQ1M2FiYy03NDdlLTQ4MzMtYWI1ZS1jODFhMGExNDZlNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDYyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTg1NzgwMTlmYmQ0MmE4ZmIyY2ZkZDJkMmNkMTM2YTdjZmQ2YjIxMjdlYzA1OGE2Y2M0ZmQ4NWVhYTQ0Y2FkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L440jRH-HDDdBaccjd64jr_3ic70yupQ94QWKf5pc-s"> ![image2018-1-17 16_9_26](https://private-user-images.githubusercontent.com/1289896/320691996-badb3a7f-8cce-462a-9334-0fe43316411b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDQzMjIsIm5iZiI6MTcxMjY0NDAyMiwicGF0aCI6Ii8xMjg5ODk2LzMyMDY5MTk5Ni1iYWRiM2E3Zi04Y2NlLTQ2MmEtOTMzNC0wZmU0MzMxNjQxMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDYyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNlOTBiNmRkMGRlODcxMmE4NTFlNDdmMjg0ZWY3ZDE1OWNkNDBiOTFhZWY5ZjUxOTkyMDJkNzFmMmY5ZDkwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R86iOFQ8h3xWIlJKg9fYY0Hd94Ut7XbPMVSMjXGdRXs) ![image2018-1-17 16_9_54](https://private-user-images.githubusercontent.com/1289896/320692014-7e1723ae-bc84-41dd-962a-d610f10e74a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDQzMjIsIm5iZiI6MTcxMjY0NDAyMiwicGF0aCI6Ii8xMjg5ODk2LzMyMDY5MjAxNC03ZTE3MjNhZS1iYzg0LTQxZGQtOTYyYS1kNjEwZjEwZTc0YTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDYyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTk3ZGI1NmI3Y2Y0NzI1YTIxODgxNjYyNjczMDIwMGRmMTdiOTI2MGM0YWM0ODNlZWRiZWI3OGUwZTAxMWRhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.C3cg9rXPGP4-nYbZykGyUjiWWFerMqE4IGBnXNNTqXw)
> 
> 可以的，适配一下就行，可以贴一下你需要html的标签

标签是自定义的不是标准的html标签。如下：
测试上标标签<sup>上标</sup>  显示上标
测试下标标签<sub>下标</sub> 显示下标
<wavy>这是波浪线</wavy> 底部显示波浪线
<circle>这是文字带点</circle>  底部显示圆点
我想知道使用Text + Span如何实现这种需求？

**Comment by asasugar** [comment]
> > > 能否实现文字底部绘制波浪线或带圆点，还有文字上标和下标呢？ <img alt="QQ20240409-092356@2x" width="91" src="https://private-user-images.githubusercontent.com/1289896/320691929-e5d53abc-747e-4833-ab5e-c81a0a146e77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDQzMjIsIm5iZiI6MTcxMjY0NDAyMiwicGF0aCI6Ii8xMjg5ODk2LzMyMDY5MTkyOS1lNWQ1M2FiYy03NDdlLTQ4MzMtYWI1ZS1jODFhMGExNDZlNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDYyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTg1NzgwMTlmYmQ0MmE4ZmIyY2ZkZDJkMmNkMTM2YTdjZmQ2YjIxMjdlYzA1OGE2Y2M0ZmQ4NWVhYTQ0Y2FkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L440jRH-HDDdBaccjd64jr_3ic70yupQ94QWKf5pc-s"> ![image2018-1-17 16_9_26](https://private-user-images.githubusercontent.com/1289896/320691996-badb3a7f-8cce-462a-9334-0fe43316411b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDQzMjIsIm5iZiI6MTcxMjY0NDAyMiwicGF0aCI6Ii8xMjg5ODk2LzMyMDY5MTk5Ni1iYWRiM2E3Zi04Y2NlLTQ2MmEtOTMzNC0wZmU0MzMxNjQxMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDYyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNlOTBiNmRkMGRlODcxMmE4NTFlNDdmMjg0ZWY3ZDE1OWNkNDBiOTFhZWY5ZjUxOTkyMDJkNzFmMmY5ZDkwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R86iOFQ8h3xWIlJKg9fYY0Hd94Ut7XbPMVSMjXGdRXs) ![image2018-1-17 16_9_54](https://private-user-images.githubusercontent.com/1289896/320692014-7e1723ae-bc84-41dd-962a-d610f10e74a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDQzMjIsIm5iZiI6MTcxMjY0NDAyMiwicGF0aCI6Ii8xMjg5ODk2LzMyMDY5MjAxNC03ZTE3MjNhZS1iYzg0LTQxZGQtOTYyYS1kNjEwZjEwZTc0YTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDYyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTk3ZGI1NmI3Y2Y0NzI1YTIxODgxNjYyNjczMDIwMGRmMTdiOTI2MGM0YWM0ODNlZWRiZWI3OGUwZTAxMWRhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.C3cg9rXPGP4-nYbZykGyUjiWWFerMqE4IGBnXNNTqXw)
> > 
> > 
> > 可以的，适配一下就行，可以贴一下你需要html的标签
> 
> 标签是自定义的不是标准的html标签。如下：
> 
> ```
> 1、测试上标标签<sup>上标</sup>  显示上标
> 2、测试下标标签<sub>下标</sub> 显示下标
> 3、<wavy>这是波浪线</wavy> 底部显示波浪线
> 4、<circle>这是文字带点</circle> 底部显示圆点
> ```
> 
> 使用Text + Span如何实现这种需求？

很遗憾，试了一下，目前Span内还不支持设置offset属性进行定位，暂不支持，但是建议升级v1.0.3版本
