### ISSUE TITLE
我自己基于你的代码做了一个StyledString支持的feature，目前已经在公司内部测试通过了。求拉我，我建个分支提交代码

### ISSUE THREAD

**Issue by CodeSlaveZhang** [asasugar/HPRichText#50]
rt

**Comment by asasugar** [comment]
你拉取一下master分支最新代码，然后跑一下entry下的所有例子代码
<img width="505" alt="image" src="https://github.com/user-attachments/assets/b6fbe6ea-3e70-494d-a280-4c2f8799e40b">
或者提一个Pull requests上来，我跑一下例子

**Comment by CodeSlaveZhang** [comment]
OK 我先拉一下master分支，代码集成进来还需要去掉一些我们公司自定义的需求的代码，要花点时间。搞定之后推一个request给你

**Comment by asasugar** [comment]
运行没问题之后贡献者中加一下你自己

> OK 我先拉一下master分支，代码集成进来还需要去掉一些我们公司自定义的需求的代码，要花点时间。搞定之后推一个request给你

好～你验证之后都先拉一下master代码，因为我随时会提交一些修复的代码，你可以fork一下，后面提个pr上来，我在 README中加入了贡献者，你提交 PR之后会自动添加到贡献者中
