### ISSUE TITLE
希望可以自定义标签的基础样式，以及增加lineHeight基准参数

### ISSUE THREAD

**Issue by nemo011** [asasugar/HPRichText#54]
1、_baseFontSize、baseFontColor属性能否支持Resource类型_（鸿蒙本身不支持的话请忽略）
2、项目对a标签的渲染有指定的基础样式，是否能在CustomHandler增加setHtmlAttributes函数，并在大概下面的代码处获取项目自定义的样式

> // 子节点继承父节点样式(需要排除不需要继承的样式)
    let htmlStyles = {};
    htmlStyles = setHtmlAttributes(this.baseFontSize, this.baseFontColor, node.tag);

3、能否增加lineHeight属性的基准参数

**Comment by asasugar** [comment]
> 1、_baseFontSize、baseFontColor属性能否支持Resource类型_（鸿蒙本身不支持的话请忽略） 2、项目对a标签的渲染有指定的基础样式，是否能在CustomHandler增加setHtmlAttributes函数，并在大概下面的代码处获取项目自定义的样式
> 
> > // 子节点继承父节点样式(需要排除不需要继承的样式)
> > let htmlStyles = {};
> > htmlStyles = setHtmlAttributes(this.baseFontSize, this.baseFontColor, node.tag);
> 
> 3、能否增加lineHeight属性的基准参数

1. 支持；
2. 我暴露一下 `common/utils/css/index.ts` 中定义的方法，本质上 `CustomHandler` 是期望使用者完全自定义功能，跟这个方法耦合感觉不大好;
3. lineHeight暂不打算支持，可以外层设置 line-height

**Comment by asasugar** [comment]
例子参考 Example_15
