### ISSUE TITLE
span背景色不生效

### ISSUE THREAD

**Issue by pipti** [asasugar/HPRichText#57]
同标题

**Comment by pipti** [comment]
应该是span外面包一层块标签就不显示背景，例如<p><span style="background-color:red">fffffff</span></p>，或者<div><span style="background-color:red">fffffff</span></div>

**Comment by asasugar** [comment]
确实存在这个问题🥲
1. 因为html中的行内标签是通过鸿蒙的 `Span` 来渲染的，但是 `Span` 不支持设置背景色；
2. 另外，如：`<span style="background-color: red">我是带背景色的span标签</span>111` ，111 也会被渲染到红色背景中，因为背景色值是设置在Text 标签中：

**Comment by asasugar** [comment]
> 确实存在这个问题🥲
> 
> 1. 因为html中的行内标签是通过鸿蒙的 `Span` 来渲染的，但是 `Span` 不支持设置背景色；
> 2. 另外，如：`<span style="background-color: red">我是带背景色的span标签</span>111` ，111 也会被渲染到红色背景中，因为背景色值是设置在Text 标签中，实际被渲染成：
>    `Text(){ Span('我是带背景色的span标签') Span('111') }.backgroundColor('red')`；
>    暂时没想到好的解决方案，尽量先避免吧

计划改造 `Span` 渲染，将会支持这个，主要使用标签 `ContainerSpan` 
https://github.com/asasugar/HPRichText/issues/13
