### ISSUE TITLE
在ListItem中使用会报错

### ISSUE THREAD

**Issue by jackqinling** [asasugar/HPRichText#58]
![2948ce0cd21818c2c1136f81bcda6133](https://github.com/user-attachments/assets/6043b344-e51a-47a8-83f6-18feb38a30b2)
![2f32c8853b3cf00b7c88fce670416ba0](https://github.com/user-attachments/assets/777a787d-de7a-4083-9642-5593a4b0c49a)

**Comment by asasugar** [comment]
因为item是常规的类型，而richTextOption是RichTextOption类型，@Link定义的不支持，需要使用@Observed和@ObjectLink改造

**Comment by asasugar** [comment]
直接改造 HPRichText 会影响用法，我新增一个专门需要动态设置的 HPRichText 组件吧

**Comment by asasugar** [comment]
用法参考：https://github.com/asasugar/HPRichText/blob/master/entry/src/main/ets/pages/Example_17.ets
