### ISSUE TITLE
HPRichText如何支持`maxLine`属性？

### ISSUE THREAD

**Issue by kylin17** [asasugar/HPRichText#59]
如题，如果限定内容的行数？（不是通过`content`中的`html`内容）

另外，在支持限定行数的情况下，如何支持通过控件来设置`textOverflow`？（不是通过`content`中`html`的`text-overflow`，因为内容很多是不可控的）

**Comment by asasugar** [comment]
> 如题，如果限定内容的行数？（不是通过`content`中的`html`内容）
> 
> 另外，在支持限定行数的情况下，如何支持通过控件来设置`textOverflow`？（不是通过`content`中`html`的`text-overflow`，因为内容很多是不可控的）

不支持，maxLine 只对 Text标签有效
