### ISSUE TITLE
如何控制文字大小啊

### ISSUE THREAD

**Issue by Er3c** [asasugar/HPRichText#6]
你好，我看了源码还是不太清楚如何控制文字大小，能给解答一下吗？

**Comment by asasugar** [comment]
> 你好，我看了源码还是不太清楚如何控制文字大小，能给解答一下吗？

后续版本会支持一下配置基础文字大小

**Comment by asasugar** [comment]
> 你好，我看了源码还是不太清楚如何控制文字大小，能给解答一下吗？

可以直接设置html标签的style设置font-size大小

**Comment by asasugar** [comment]
@Er3c 支持了配置baseFontSize属性，具体看提交记录，v1.0.3包会更新～

**Comment by LyonUp** [comment]
> @Er3c 支持了配置baseFontSize属性，具体看提交记录，v1.0.3包会更新～

baseFontColor 是不是也有使用场景

**Comment by asasugar** [comment]
> 默认的文字大小、颜色、粗细，应该和 textProp 里的 无样式 textOption 保持一致比较好吧？

目前支持默认样式的字号会根据设置的baseFontSize 按照一定比例改变

**Comment by Er3c** [comment]
> @Er3c 支持了配置baseFontSize属性，具体看提交记录，v1.0.3包会更新～

更新到了1.0.3了，解决了一个needScroll之前异常的问题，但是baseFontSize不生效不知道是什么原因
