### ISSUE TITLE
html富文本中img标签能加载项目中的本地资源图片吗

### ISSUE THREAD

**Issue by tanjt223** [asasugar/HPRichText#67]
html富文本中img标签怎么加载项目中的本地资源图片？

如项目中有一张本地图片，路径：resouces/base/media/a.png,
img标签中怎么加载图片 
```typescript
<img src="xxxxxxx"/>
```

**Comment by asasugar** [comment]
1.  `<img width="500px" resource="1" src="app.media.icon" />` 增加resource 标识，然后src 传入本地resource 资源路径；
2. `Image` builder判断标识 `Image(item.attr?.resource ? $r(item.attr?.src) : item.attr?.src)` （不需要关心这个）；
