### ISSUE TITLE
现在支持一行排列效果是：图1、图2、文本，这种吗？

### ISSUE THREAD

**Issue by tanjt223** [asasugar/HPRichText#68]
问题： 现在一行排列：图1、图2、文本
我尝试使用内联或浮动排列，但并不起作用，每张图片还是单独占满一行，怎么还不支持这种是吗

![image](https://github.com/user-attachments/assets/0593b9ae-2abf-494c-a448-ca6e514bce11)

**Comment by lanyueyin** [comment]
兄弟，我看你好像在鸿蒙开发交流4群问过
  
你这种方式需要在作者的源代码上进行修改，源代码使用Column布局的：
![1729288325200](https://github.com/user-attachments/assets/1252515a-51d0-424a-be8c-b8f6087bc64c)

此处需要改成Text，在里面添加Span和ImageSpan，这是我修改之后的运行图：
![1729288451309](https://github.com/user-attachments/assets/f63c002f-995f-4877-80a7-a2d3c7de9287)

附上修改的代码文件：https://pan.baidu.com/s/1fh00UATlkro4E5YQNRL5mw?pwd=w24k
调用方式与作者的一般无二，只需把HPRichText替换成文件中的FormHPRichText即可，希望作者能看到，支持这种方式

**Comment by asasugar** [comment]
> 兄弟，我看你好像在鸿蒙开发交流4群问过
> 
> 你这种方式需要在作者的源代码上进行修改，源代码使用Column布局的： ![1729288325200](https://private-user-images.githubusercontent.com/48479213/378020874-1252515a-51d0-424a-be8c-b8f6087bc64c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTIxNjYsIm5iZiI6MTcyOTY1MTg2NiwicGF0aCI6Ii80ODQ3OTIxMy8zNzgwMjA4NzQtMTI1MjUxNWEtNTFkMC00MjRhLWJlOGMtYjhmNjA4N2JjNjRjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAyNTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NWExNTZiNjRkMzJmYmU2N2Y4NDliMTcyMDg5MzRlOGQzMjU3NjcyMDY2YWRmMGIzZmJmYTc3MDJlODIyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tPognhEQAuh9fHO_lXPx3boffuAY0k-ZuMboi54HIL8)
> 
> 此处需要改成Text，在里面添加Span和ImageSpan，这是我修改之后的运行图： ![1729288451309](https://private-user-images.githubusercontent.com/48479213/378021031-f63c002f-995f-4877-80a7-a2d3c7de9287.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTIxNjYsIm5iZiI6MTcyOTY1MTg2NiwicGF0aCI6Ii80ODQ3OTIxMy8zNzgwMjEwMzEtZjYzYzAwMmYtOTk1Zi00ODc3LTgwYTctYTJkM2M3ZGU5Mjg3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAyNTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMTg4NzA4Y2EyMDc3ODBlNTJlMjBjNzhkMDdiZDA2ZDkzOWY0MmI3YmU3N2IzMTRhZGY5MzU3MmY1YWUwNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jZkVz43kMxAy44BpTEuTvhjNssZB6Qyik6aCl-oeZ8I)
> 
> 附上修改的代码文件：https://pan.baidu.com/s/1fh00UATlkro4E5YQNRL5mw?pwd=w24k 调用方式与作者的一般无二，只需把HPRichText替换成文件中的FormHPRichText即可，希望作者能看到，支持这种方式

直接改这，有些场景会影响渲染，你可以验证下entry下的例子

**Comment by asasugar** [comment]
1. 更新到 `v3.0.4` 版本;
2. 通过这种方式来 fix：
 ```ts
this.richTextModel.richTextOption = {
      content: `
      <div><img width="100px" resource="1" src="app.media.icon" /><img width="100px" resource="1" src="app.media.icon" /><span>span文本</span></div>
    `,
```
