### ISSUE TITLE
@State richTextOption: RichTextOption = {     "content": '',   }

### ISSUE THREAD

**Issue by Chang-Chen** [asasugar/HPRichText#7]
HPRichText({
          richTextOption: this.richTextOption,
          needScroll: false,
          onLinkPress: (e) => {
            return e;
          }
        })

通过接口动态更改
this.richTextOption = {
          "content": noticeData.context ?? ''
        };

页面UI没变化

**Comment by asasugar** [comment]
v1.0.4 版本已修复，等审核通过更新一下～ @Chang-Chen

**Comment by asasugar** [comment]
<img width="278" alt="image" src="https://github.com/asasugar/HPRichText/assets/27256120/a2cd37b4-e352-4bc9-a846-9d2c79662072">
<img width="269" alt="image" src="https://github.com/asasugar/HPRichText/assets/27256120/b9aebab1-d515-4854-be70-8869ff747e3f">
