### ISSUE TITLE
在列表中使用该富文本组件还是会卡顿

### ISSUE THREAD

**Issue by Echollk-GIF** [asasugar/HPRichText#70]
import RichTextCargoList from '../../common/component/RichTextCargoList/RichTextCargoList'
import { HPRichText } from '@ohasasugar/hp-richtext';
import type { RichTextOption } from '@ohasasugar/hp-richtext';

interface TextClazz {
  type: number,
  text: string,
}

@Reusable
@Component
struct RichTextCom {
  @Prop text: string = ''
  @Prop type: number = 0
  @Prop index: number = 0

  @State richTextOption: RichTextOption = {
    content: `
    <font  style='font-size:18px;'>南京 雨花台 → 淮北 相山</font> <img src=\"https://imagecdn.ymm56.com/ymmfile/static/image/match/render/carpoolingImg3xV5.png\" height='18' width='34'/>
    <font color='#666666' style='font-size:16px;'>4.2米<font color='#CCCCCC'> | </font>高栏<font color='#CCCCCC'> | </font>2吨</font>
    <font color='#999999' style='font-size:15px;'>衣服 纸箱 <font color='#FF7000'>今天装货</font> 一装一卸</font>
    <font color='#999999' style='font-size:12px;'>交易334</font>
    `,
    imageProp: {
      webp: true,
    }
  }

  build() {
    Row() {
      HPRichText({
        richTextOption: $richTextOption,
        needScroll: true,
        onLinkPress: (e) => {
          return e;
        }
      })
      // if (this.type === 1) {
      //   RichText(this.text)
      //     .width('100%')
      //     .height(40)
      //     .hitTestBehavior(HitTestMode.None)
      // } else {
      //   Text(this.text)
      //     .height(40)
      //     .textAlign(this.index % 2 === 0 ? TextAlign.Start : TextAlign.End)
      //     .width('100%')
      // }
    }
  }
}

@Component
export default struct TestPage {
  @State list: TextClazz[] = []
  private dataSource = new CommonDataSource<TextClazz>()

  aboutToAppear(): void {
    for (let i = 0; i < 30; i++) {
      // let itemData: TextClazz = {
      //   type: 0,
      //   text: 'hello ' + i
      // }
      // if (i % 10 === 0 || i <= 15) {
      //   itemData = {
      //     type: 1,
      //     text: "回复<font color='#F23476' style='font-size:36px;font-color:red'><a href='app://users/profile?user_id=63156880'>@善良的咩咩羊</a><font>rtdsfs</font></font>：推广姑姑<font style='font-size:54px;font-color:blue;'>你好<span style='color:#ff0000'>" + i + "testcolore</span></font>"
      //   }
      // }
      let itemData: TextClazz = {
        type: 1,
        text: "回复<font color='#F23476' style='font-size:36px;font-color:red'><a href='app://users/profile?user_id=63156880'>@善良的咩咩羊</a><font>rtdsfs</font></font>：推广姑姑<font style='font-size:54px;font-color:blue;'>你好<span style='color:#ff0000'>" +
          i + "testcolore</span></font>"
      }
      this.list.push(itemData)
    }
    this.dataSource.setData(this.list)
  }

  build() {
    Column() {
      List() {
        LazyForEach(this.dataSource, (item: TextClazz, index: number) => {
          ListItem() {
            Column() {
              RichTextCom({ text: item.text, type: item.type, index: index })
            }.margin({ bottom: 20 })
          }
        }, (item: TextClazz) => JSON.stringify(item))
      }
      .cachedCount(1000)
      .constraintSize({ maxWidth: '100%' })
      .height('100%')
      .width('100%')
      .margin({ left: 16, right: 16 })
    }
    .width('100%')
    .height('100%')
  }
}

// CommonDataSource.ets
export class CommonDataSource<T> implements IDataSource {
  private listeners: DataChangeListener[] = [];
  protected originDataArray: T[] = [];

  totalCount(): number {
    return this.originDataArray.length;
  }

  getAllData(): T[] {
    return this.originDataArray
  }

  getData(index: number) {
    return this.originDataArray[index];
  }

  addData(index: number, data: T): void {
    this.originDataArray.splice(index, 0, data);
    this.notifyDataAdd(index);
  }

  pushData(data: T): void {
    this.originDataArray.push(data);
    this.notifyDataAdd(this.originDataArray.length - 1);
  }

  pushDataArray(...items: T[]): void {
    for (let data of items) {
      this.originDataArray.push(data);
      this.notifyDataAdd(this.originDataArray.length - 1);
    }
  }

  deleteDataUseContent(data: T): void {
    let delIndex: number = -1
    for (let index = 0; index < this.originDataArray.length; index++) {
      const element = this.originDataArray[index];
      if (data === element) {
        delIndex = index
      }
    }
    if (delIndex != -1) {
      this.deleteData(delIndex)
    }
  }

  deleteData(index: number): void {
    this.originDataArray.splice(index, 1);
    this.notifyDataDelete(index);
  }

  clear() {
    this.originDataArray.splice(0, this.originDataArray.length)
    this.listeners.forEach(listener => {
      listener.onDataDelete(0)
    })
  }

  setData(dataArray?: T[]) {
    if (dataArray) {
      this.originDataArray = dataArray
    } else {
      this.originDataArray = []
    }
    this.notifyDataReload()
  }

  registerDataChangeListener(listener: DataChangeListener): void {
    if (this.listeners.indexOf(listener) < 0) {
      this.listeners.push(listener);
    }
  }

  unregisterDataChangeListener(listener: DataChangeListener): void {
    const pos = this.listeners.indexOf(listener);
    if (pos >= 0) {
      this.listeners.splice(pos, 1);
    }
  }

  notifyDataReload() {
    this.listeners.forEach(listener => {
      listener.onDataReloaded();
    })
  }

  notifyDataAdd(index: number) {
    this.listeners.forEach(listener => {
      listener.onDataAdd(index);
    })
  }

  notifyDataMove(from: number, to: number) {
    this.listeners.forEach(listener => {
      listener.onDataMove(from, to);
    })
  }

  notifyDataDelete(index: number) {
    this.listeners.forEach(listener => {
      listener.onDataDelete(index);
    })
  }

  notifyDataChange(index: number) {
    this.listeners.forEach(listener => {
      listener.onDataChange(index);
    })
  }
}

示例代码如上，按道理说已经转化为基本组件了，列表不应该卡顿的，请问为什么还是会卡顿呢

**Comment by Echollk-GIF** [comment]
之前的代码发现是在api12版本下使用了v1版本，试了一下在api 12版本下使用如下代码还是卡顿
import { HPRichTextV2, RichTextOptionModelV2 } from '@ohasasugar/hp-richtext';

@Entry
@Component
export default struct Index {
  @State arr: RichTextOptionModelV2[] = []


  // 模拟请求接口数据
  aboutToAppear(): void {
    for (let i = 0; i < 40; i++) {
      let o = new RichTextOptionModelV2();
      o.richTextOption.content = `<font  style='font-size:18px;'>南京 ${i} 雨花台 → 淮北 相山</font> <img src=\"https://imagecdn.ymm56.com/ymmfile/static/image/match/render/carpoolingImg3xV5.png\" height='18' width='34'/>
<font color='#666666' style='font-size:16px;'>4.2米<font color='#CCCCCC'> | </font>高栏<font color='#CCCCCC'> | </font>2吨</font>
<font color='#999999' style='font-size:15px;'>衣服 纸箱 <font color='#FF7000'>今天装货</font> 一装一卸</font>
<font color='#999999' style='font-size:12px;'>交易334</font>`;
      this.arr.push(o)
    }
  }

  build() {
    Column() {
      List({ space: 10 }) {
        ForEach(this.arr, (item: RichTextOptionModelV2) => {
          ListItem() {
            HPRichTextV2({
              richTextModel: item
            })
              .width('100%')
              .height(100)
              .borderRadius(10)
              .backgroundColor(0x007DFF)
          }
        }, (item: number) => JSON.stringify(item))
      }
    }
    .padding(12)
    .height('100%')
    .backgroundColor(0xF1F3F5)
  }
}

**Comment by asasugar** [comment]
> 之前的代码发现是在api12版本下使用了v1版本，试了一下在api 12版本下使用如下代码还是卡顿 import { HPRichTextV2, RichTextOptionModelV2 } from '@ohasasugar/hp-richtext';
> 
> @entry @component export default struct Index { @State arr: RichTextOptionModelV2[] = []
> 
> // 模拟请求接口数据 aboutToAppear(): void { for (let i = 0; i < 40; i++) { let o = new RichTextOptionModelV2(); o.richTextOption.content = `<font style='font-size:18px;'>南京 ${i} 雨花台 → 淮北 相山</font> <img src=\"https://imagecdn.ymm56.com/ymmfile/static/image/match/render/carpoolingImg3xV5.png\" height='18' width='34'/> <font color='#666666' style='font-size:16px;'>4.2米<font color='#CCCCCC'> | </font>高栏<font color='#CCCCCC'> | </font>2吨</font> <font color='#999999' style='font-size:15px;'>衣服 纸箱 <font color='#FF7000'>今天装货</font> 一装一卸</font> <font color='#999999' style='font-size:12px;'>交易334</font>`; this.arr.push(o) } }
> 
> build() { Column() { List({ space: 10 }) { ForEach(this.arr, (item: RichTextOptionModelV2) => { ListItem() { HPRichTextV2({ richTextModel: item }) .width('100%') .height(100) .borderRadius(10) .backgroundColor(0x007DFF) } }, (item: number) => JSON.stringify(item)) } } .padding(12) .height('100%') .backgroundColor(0xF1F3F5) } }

```ts
aboutToAppear(): void {
    for (let i = 0; i < 40; i++) {
      let o = new RichTextOptionModelV2();
      o.richTextOption.content =
        `<font style='font-size:18px;'>南京 ${i} 雨花台 → 淮北 相山</font> <img src=\"https://imagecdn.ymm56.com/ymmfile/static/image/match/render/carpoolingImg3xV5.png\" height='18' width='34'/> <font color='#666666' style='font-size:16px;'>4.2米<font color='#CCCCCC'> | </font>高栏<font color='#CCCCCC'> | </font>2吨</font> <font color='#999999' style='font-size:15px;'>衣服 纸箱 <font color='#FF7000'>今天装货</font> 一装一卸</font> <font color='#999999' style='font-size:12px;'>交易334</font>`;
      o.needScroll = false; // 禁用Scroll
      this.arr.push(o);
    }
  }
```
