### ISSUE TITLE
内联图片与文字没有垂直居中

### ISSUE THREAD

**Issue by Echollk-GIF** [asasugar/HPRichText#71]
兼容内联图片展示这个更新后，两边加上<div>的确可以使图片内联展示，但是文字与图片没有垂直居中。
例如富文本：
`"<div><font  style='font-size:18px;'>南京 雨花台 → 北京 大兴</font> <img src=\"https://imagecdn.ymm56.com/ymmfile/static/appUpdate/buyOutIcon1@3x.png\" height='18' width='44'/><img src=\"https://imagecdn.ymm56.com/ymmfile/static/appUpdate/buyOutIcon1@3x.png\" height='18' width='44'/></div>" `
         效果如下：
         
![image](https://github.com/user-attachments/assets/27355a5c-9f92-408d-811c-41c2cf0f551e)

**Comment by asasugar** [comment]
1. 给图片加一下 `style="margin: 0 0 5px 0"` 。
2. 等`3.0.3`版本，这边需要更新一下 `margin`属性的获取，详见
至于为什么加`vertical-align` 无效？因为 `img` 标签不是用 `ImageSpan` 渲染，而是通过 `Image` ，它不支持鸿蒙的`verticalAlign`属性
