### ISSUE TITLE
富文本嵌套的情况下，存在里层嵌套的应该展示的空格被吃掉导致不展示的问题

### ISSUE THREAD

**Issue by Echollk-GIF** [asasugar/HPRichText#72]
例如富文本
`"<font color='#666666' style='font-size:14px;'>6.8米<font color='#CCCCCC'>  |  </font>高栏<font color='#CCCCCC'>  |  </font>5~6吨<font color='#CCCCCC'>  |  </font>5~6方</font>"`
里面嵌套的竖杠两边的空格就不会展示出来了，效果如下
![image](https://github.com/user-attachments/assets/af1a8334-75d0-4573-afe0-44489c2283f0)

**Comment by asasugar** [comment]
> 例如富文本 `"<font color='#666666' style='font-size:14px;'>6.8米<font color='#CCCCCC'> | </font>高栏<font color='#CCCCCC'> | </font>5~6吨<font color='#CCCCCC'> | </font>5~6方</font>"` 里面嵌套的竖杠两边的空格就不会展示出来了，效果如下 ![image](https://private-user-images.githubusercontent.com/84825932/379855750-af1a8334-75d0-4573-afe0-44489c2283f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTU4ODQsIm5iZiI6MTczMDQ1NTU4NCwicGF0aCI6Ii84NDgyNTkzMi8zNzk4NTU3NTAtYWYxYTgzMzQtNzVkMC00NTczLWFmZTAtNDQ0ODljMjI4M2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwMDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMDE5MWEzY2ZkMGQ4OTU1M2IxNTAwODRkMzhjZTE1NTNiMGRhZjMyMDk4MDM1ZWQyNjU3MTg3NTI3MWUyN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GtWs4tgU2h7wHR_gwAPlf1v3OkKb5Tshsn_YglWd-1k)

`<font color='#CCCCCC'>\t\t\t|\t\t\t</font>`
