### ISSUE TITLE
生成的组件自身无法响应点击事件，并且给它的父级元素设置点击事件，生成的组件的区域也无法响应点击事件

### ISSUE THREAD

**Issue by Echollk-GIF** [asasugar/HPRichText#74]
例如：
HPRichTextV2({
                richTextModel: "<font  style='font-size:18px;'>南京 雨花台 → 北京 东城</font>"
              })
createRichTextModel(richStr: string): RichTextOptionModelV2 {
    let richText = new RichTextOptionModelV2();
    richText.richTextOption.content = richStr;
    richText.onLinkPress这里也设置可点击事件
    return richText;
  }
生成的富文本组件，父级元素和自身元素都不支持响应点击事件。
这个问题有点严重，大片使用该组件解析富文本的区域都不可点击了

**Comment by asasugar** [comment]
提供一下完整的代码吧，写的有点乱
