### ISSUE TITLE
请问如何设置行间距和字间距呢

### ISSUE THREAD

**Issue by RaphetS** [asasugar/HPRichText#76]

**Comment by asasugar** [comment]
`
this.richTextModel.richTextOption = {
      content: `
      <p style="margin: 20 0 0 0;letter-spacing: 10px">我是行1</p>
      <p style="margin: 20 0 0 0;letter-spacing: 10px">我是行2</p>
    `
    }
`

**Comment by asasugar** [comment]
<img width="314" alt="image" src="https://github.com/user-attachments/assets/9056e995-4ed6-44db-b3cb-27c726c5177a">
