### ISSUE TITLE
能否考虑一下将RichTextOption拆分，content和样式属性进行拆分，避免重复渲染

### ISSUE THREAD

**Issue by WeiYuanlin** [asasugar/HPRichText#78]
```ts
  @Link @Watch('onUpdateRichTextOption') richTextOption: RichTextOption;

export interface RichTextOption {
  content: string;
  baseFontSize?: number | Resource;
  baseFontColor?: string | Resource;
  basePixelUnit?: PixelUnit;
  basePixelRatio?: number | Resource;
  imageProp?: ImageProp;
  customHandler?: CustomHandler;
}

```
目前整个富文本配置项，是通过一个option传递过来的，然而这样有一个问题，当我修改默认样式例如字体颜色baseFontColor和字号baseFontSize，其实是不需要进行整个dom结构重新解析生成的。拆分后，只需要监听content变化，他来决定是否重新进行解析生成组件dom树。目前修改默认样式属性，会导致重新生成组件树，使得整个富文本组件重新渲染，当存在图片（通过customHandler中修改尺寸）时候，有存在非常明显的闪烁。

**Comment by asasugar** [comment]
> ```ts
>   @Link @Watch('onUpdateRichTextOption') richTextOption: RichTextOption;
> 
> export interface RichTextOption {
>   content: string;
>   baseFontSize?: number | Resource;
>   baseFontColor?: string | Resource;
>   basePixelUnit?: PixelUnit;
>   basePixelRatio?: number | Resource;
>   imageProp?: ImageProp;
>   customHandler?: CustomHandler;
> }
> ```
> 
> 目前整个富文本配置项，是通过一个option传递过来的，然而这样有一个问题，当我修改默认样式例如字体颜色baseFontColor和字号baseFontSize，其实是不需要进行整个dom结构重新解析生成的。拆分后，只需要监听content变化，他来决定是否重新进行解析生成组件dom树。目前修改默认样式属性，会导致重新生成组件树，使得整个富文本组件重新渲染，当存在图片（通过customHandler中修改尺寸）时候，有存在非常明显的闪烁。

修改默认样式需要重新设置节点的样式属性，会导致重刷
