### ISSUE TITLE
font-family 字体带引号会闪退

### ISSUE THREAD

**Issue by anthonyY** [asasugar/HPRichText#79]
下面这种数据会闪退，font-family 字体带引号的情况会闪退，如'Segoe UI'，麻烦看看能不能解决，谢谢！

<span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">我国国旗上有（）个星星？</span>

**Comment by anthonyY** [comment]
上面发的自动变成html渲染调了，应该看这里
```
<span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">我国国旗上有（）个星星？</span>
```

**Comment by asasugar** [comment]
根据官方文档目前只支持持'HarmonyOS Sans'字体和[注册自定义字体](https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-font-V5)
参考链接：https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/ts-universal-attributes-text-style-V5#fontfamily

HPRichText自定义字体目前还不支持
