### ISSUE TITLE
填充的富文本内有图片，内联样式设置的width很宽，怎么进行更改覆盖

### ISSUE THREAD

**Issue by Chang-Chen** [asasugar/HPRichText#8]
填充的富文本内有图片，内联样式设置的width很宽，怎么进行更改覆盖

`<p><img src="https://systems-img.oss-cn-shanghai.aliyuncs.com/2021-03-26/mg21312tfei2sptz5zcp.png?Expires=3194562220&amp;OSSAccessKeyId=LTAIT6aoJq1DlSON&amp;Signature=jpnY0PFazwcz69S1qb0tilHMwuA%3D" alt="" width="654" height="1281" /></p>`

![image](https://github.com/asasugar/HPRichText/assets/37439847/d78b07ff-2cf8-4f5d-807d-a5348e93516d)

**Comment by asasugar** [comment]
> 填充的富文本内有图片，内联样式设置的width很宽，怎么进行更改覆盖
> 
> `<p><img src="https://systems-img.oss-cn-shanghai.aliyuncs.com/2021-03-26/mg21312tfei2sptz5zcp.png?Expires=3194562220&amp;OSSAccessKeyId=LTAIT6aoJq1DlSON&amp;Signature=jpnY0PFazwcz69S1qb0tilHMwuA%3D" alt="" width="654" height="1281" /></p>`
> 
> ![image](https://private-user-images.githubusercontent.com/37439847/328126469-d78b07ff-2cf8-4f5d-807d-a5348e93516d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzM4NDksIm5iZiI6MTcxNTA3MzU0OSwicGF0aCI6Ii8zNzQzOTg0Ny8zMjgxMjY0NjktZDc4YjA3ZmYtMmNmOC00ZjVkLTgwN2QtYTUzNDhlOTM1MTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA5MTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMmQwNTdiMGI0YjNlOGUyODhkNThhODU5NDQ0YzZmY2NiYjEzYWMyZmI0YzE3ZDcwODgzZTUyOTlmMTY4M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.br_DhLeQg44agZNIFTmhkbbmLpSnXA00PzQX22xkIqs)

不写单位，在鸿蒙中会默认转化为 `vp` 单位，你可以设置 width="654px" height="1281px" 或者在style中设置
