### ISSUE TITLE
p标签中有 font-family  不能解析

### ISSUE THREAD

**Issue by Topdear** [asasugar/HPRichText#80]
示例：
"<p style=\"margin-top: 10px; margin-bottom: 10px; padding: 0px; line-height: 1.5; color: rgb(55, 56, 60); font-family: 'PingFang SC'; font-size: 16px !important;\">xxxxxxxx</p>"

去掉：font-family: 'PingFang SC' 就好了。

**Comment by Topdear** [comment]
另外一个问题 如果有2个换行符 <br/><br/>只解析了一个。

**Comment by Topdear** [comment]
另外一个问题 如果有2个换行符 <br/><br/>只解析了一个。

**Comment by asasugar** [comment]
https://github.com/asasugar/HPRichText/issues/79
