### ISSUE TITLE
富文本内的a标签无法点击

### ISSUE THREAD

**Issue by LJZJIANG** [asasugar/HPRichText#82]
富文本内的a标签无法点击

**Comment by asasugar** [comment]
目前 `a` 标签支持触发回调 `href` 设置的链接，你如果指的是 `onClick` 事件的话，确实被拦截了。
你需要用`其他标签`绑定 `onClick` 事件，可以参考[Index_5.ets](https://github.com/asasugar/HPRichText/blob/master/entry/src/main/ets/pages/V2/Index_5.ets)
