### ISSUE TITLE
下划线颜色没效果，和上下边距问题

### ISSUE THREAD

**Issue by jikanghui** [asasugar/HPRichText#85]
大神你好，感谢开源，我发现两个问题，希望后续版本可以优化：
1.html文本中设置了颜色，内部加了下划线标签，颜色没对下划线起作用
2.上下有多余内边距，而左右没有

html文本：
`<p><span style="font-size:14px"><span style="color:#07a9fe"><u>销售人员：</u></span>需要提醒您的是，此次录音录像过程对于今后您维护权益非常关键，请您认真阅读您签署文件的具体内容，如实回答相关问题，如果销售人员向您作出任何与书面文件内容不一致的承诺，建议您与销售人员通过书面形式予以确认，以便更好地维护您的合法权益。</span></p>`
![微信图片_20241120153410](https://github.com/user-attachments/assets/3f1c50ff-ab3f-41e8-8998-765605346fb3)

**Comment by asasugar** [comment]
> 大神你好，感谢开源，我发现两个问题，希望后续版本可以优化： 1.html文本中设置了颜色，内部加了下划线标签，颜色没对下划线起作用 2.上下有多余内边距，而左右没有
> 
> html文本： `<p><span style="font-size:14px"><span style="color:#07a9fe"><u>销售人员：</u></span>需要提醒您的是，此次录音录像过程对于今后您维护权益非常关键，请您认真阅读您签署文件的具体内容，如实回答相关问题，如果销售人员向您作出任何与书面文件内容不一致的承诺，建议您与销售人员通过书面形式予以确认，以便更好地维护您的合法权益。</span></p>` ![微信图片_20241120153410](https://private-user-images.githubusercontent.com/108506077/387992987-3f1c50ff-ab3f-41e8-8998-765605346fb3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MTM5NTgsIm5iZiI6MTczNTYxMzY1OCwicGF0aCI6Ii8xMDg1MDYwNzcvMzg3OTkyOTg3LTNmMWM1MGZmLWFiM2YtNDFlOC04OTk4LTc2NTYwNTM0NmZiMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQwMjU0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmU4MmE1NjdlOTU3YTc0Nzc1N2YyZGIyMmQ3NDFlOTUwM2I0NTE5NzhmYmU1MDk3NzJjNWMzNjFhMzExNmYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vhZnJ9JhnpFDRf49dpCb4-3HpsWdkglfaxXo7cujUiY)

1. 使用`text-decoration`属性设置
