### ISSUE TITLE
baseFontSize 不生效

### ISSUE THREAD

**Issue by W7-XX** [asasugar/HPRichText#9]
// 监听到richTextOption参数变化则重新触发 HTML转化函数
  onUpdateRichTextOption() {
    const htmlParser = new HTMLParser(this.richTextOption?.customHandler, this.richTextOption?.imageProp);
    this.htmlJson = htmlParser.html2json(this.richTextOption.content);
  }
 
上述方法没有将this.richTextOption?.baseFontSize传给HTMLParser，导致设置的baseFontSize无法生效

**Comment by asasugar** [comment]
> // 监听到richTextOption参数变化则重新触发 HTML转化函数 onUpdateRichTextOption() { const htmlParser = new HTMLParser(this.richTextOption?.customHandler, this.richTextOption?.imageProp); this.htmlJson = htmlParser.html2json(this.richTextOption.content); }
> 
> 上述方法没有将this.richTextOption?.baseFontSize传给HTMLParser，导致设置的baseFontSize无法生效

欢迎提下pr～或者等我这段时间忙完～
